### ISSUE TITLE
@InjectAnnotation not working with Eclipse/Gradle/net.ltgt.apt-eclipse

### ISSUE THREAD

**Issue by ChrisTrenkamp** [immutables/immutables#1077]
@InjectAnnotation works as expected when building an Immutables/Gradle project from the commandline.  However, under Eclipse, when using the net.ltgt.apt-eclipse plugin, the generated classes under .apt_generated are missing their annotations.

I'm not sure where where the problem is.  Any ideas?

**Comment by ChrisTrenkamp** [comment]
Spoke too soon.  Looks like it's simply an issue with how Eclipse's buildship handles annotation processing.

Whenever you make a change to the @InjectAnnotation, close the project, re-run `./gradlew eclipseJdtApt eclipseFactorypath eclipseJdt`, and re-open it.

Pretty clunky, but it's the only way to get Buildship to behave.

**Comment by elucash** [comment]
thank you for reporting (and closing ;) this! just some thoughts: Immutables sometimes use aggressive caching, maybe full clean rebuild can start things anew; Eclipse also have "batch" flag for annotation processing, so that all sources are inspected, not only changed ones, cannot say it's in any way relevant, but wanted to bring it up jic
