### ISSUE TITLE
Code smell: Do not use Optional as parameter

### ISSUE THREAD

**Issue by bmarwell** [immutables/immutables#1109]
This page states:
https://immutables.github.io/factory.html

However, a lot of code analyzers will not accept this code:

> Note that @Value.Default, @Value.Lazy, @Value.Derived, etc, annotations are not applicable to the parameters of factory methods. Moreover, they usually don't make sense for factory builders in the way that they do for immutable value objects.
> 
> To have default parameters, use Optional parameters:
> ```java
> @Builder.Factory
> public static int sum(Optional<Integer> a, Optional<Integer> b) {
>   return a.or(0) + b.or(0);
> }
> ```

## Reason / rationale

`java.util.Optional` is not intended for use in parameters. The example is also prone to a NPE, because, as there are no official `@Nonnull` annotations, could be nullable. Of course `null` is an anti-pattern, but still -- `Optional` is not a sane choice for parameters.

> The Java language authors have been quite frank that Optional was intended for use only as a return type, as a way to convey that a method may or may not return a value.

## Suggested fix

create a new annotation `@OptionalFactoryParamter` or similar.

## Sources

* https://stackoverflow.com/a/31923105/1549977
* https://www.dariawan.com/tutorials/java/using-java-optional-correctly/

**Comment by elucash** [comment]
I consider optional parameter perfectly fine when overloads or builders cannot provide alternative. Frankly, find arguments about them unsubstantiated, I'm aware of these believes, whatsoever.
At the same time, just making parameters `@Nullable` should solve the problem. One can use `Style.nullableAnnotation` to have own nullable annotation.

**Comment by bmhm** [comment]
Alright. I also believe that in a world, where `null` does not exist, `Optional<?>` is perfectly fine.

Maybe a common ground or compromise would be to offer alternatives on the doc page, like this:

> For the probable fact that your code style or your code analyzers do not allow `Optional` as a method parameter, here are some alternatives:
> 1. Overload methods, so that multiple `SumBuilder` classes will be generated.
> 2. Consider creating a parameter value object using `@Immutables`.
> 3. Mark the parameters as `@Nullable` and deal with the problem in your code.

Maybe something like this? I do not even know if method 1) works. Name clash?

**Comment by elucash** [comment]
Static method marked with Factory annotation is an implementation detail (whether it's public or not), and then you generate builder which is supposed to be used as API (otherwise It makes little sense), and these builders will have overloads without optionals. Implementation detail choice is up to the user. Overall, static factory builders (and, similarly, pojo-constructor builders) are niche, rarely used functionality, every time when those features are not enough, there should be a straightforward switch to immutable value type.

```java
// FROM
@Builder.Factory
public static int sum(Optional<Integer> a, Optional<Integer> b) {
  return a.or(0) + b.or(0);
}
// TO
@Immutable interface Sum {
   @Default default int a() { return 0; };
   @Default default int b() { return 0; };
   default int sum() { return a() + b(); }
}
```

Seems like obvious and not too involved. We can contribute to documentation that `... @Nullable` parameters can also be used`.

There are many more problems with people's code than fully statically typed optionals, like wrong abstractions, proliferation of utility code, high coupling and low cohesion, mutable shared structures and non-documented nullable fields, wrong usage of generics...

**Comment by bmhm** [comment]
> Seems like obvious and not too involved. We can contribute to documentation that "... @Nullable parameters can also be used here", whatever...

LGTM
