### ISSUE TITLE
configurable toString() - strategy

### ISSUE THREAD

**Issue by mickroll** [immutables/immutables#1233]
Multiple issues were created, because users of `Immutables` want to customize the content of `toString()`:
- #332 Feature request: add support for brief toString() methods
- #825 How to specify toString() method on interface?
- #758 toString of byte arrays should be represented as base64/hex
- #563 Explicitly define which fields are included in toString
  - this lead to the implementation of `@Value.Redacted`
- #898 Option to output JSON in generated toString() method

Now a colleague of mine had an idea (thanks, @famod): "How about a configurable toString - strategy?"

This is what i came up with:
1. introduce a config option: in `@Value.Style`: `Class<? extends ToStringStrategy> toStringStrategy() default DefaultToStringStrategy.class;`
2. the `DefaultToStringStrategy` works exactly like `toString()` is created now: it respects `@Redacted`, `redactedMask` and so on
3. a custom `XYZToStringStrategy` could be implemented for each of the requested features above

The artifact containing the strategy-implementation would have to be on the classpath of the annotation processor, of course.

Our use case would be an inverse annotation to `@Redacted`: we only want to include explicitely chosen attributes in `toString` - Generation. With the above config option, this could be done easily.

**Comment by elucash** [comment]
How about just ability to specify static method to wire, fully qualified (`deletateToString="whatever.packg.AnyStrategyOneWants.strigify"`) ? Minimum change and we (in Immutables don't have to drag compile/runtime dependency on strategy interface or expect it to implement any method, instantiate it, cache it or not, too many complications with strategy as an object. Slight variation would be to specify class and expect static method on it of particular name `toString` or `strigify`, but just fully qualified name as shown before serves the same in a very straightforward way.

**Comment by mickroll** [comment]
The neat thing of immutables and its source code generation is that during runtime it works completely without reflection. Having a `ToStringStrategy` like expained would facilate that.
Simply calling a static method for creating a `String`-representation would lead either to:
- a central `ToString(Object)`-Implementation, which would rely on reflection
- a dedicated static method for each immutable model interface (and manual implementation?)

Maybe a solution to this would be an overloaded static toString-method in a central helper class. Right now, i am thinking of generating this helper class as well, depending on our `IncludeInToString` annotation on any model definition.

At least we have an extension point now, thank you!

**Comment by elucash** [comment]
no reflection needed, code is generated with static method call, yes, create overloaded static method which is resolved at compile time, any other introspection (beyond overloaded ad-hoc methods) you would still have to do on your own. Strategies require managing their instances somehow or instantiating per call or per value, too much complexity/details. Regarding points/bullets, I cannot see the situation is any different with strategies: either single strategy of dedicated strategy, no benefits over overloaded static methods.

**Comment by mickroll** [comment]
> I cannot see the situation is any different with strategies: either single strategy of dedicated strategy, no benefits over overloaded static methods.

Yes i wasn't clear about that: i was talking about a toString - method-generation strategy that would run during code generation time, not a toString-strategy that is called during runtime.

With the current solution we have a clean way to link to our (to-be-generated by ourselfes) toString implementations. Thank you for this.

**Comment by elucash** [comment]
Well, I didn't get it that it was about compile time strategies. First of all, there's a problem with loading user/library level classes into annotation processing depending on if regular or special annotation classpath is used. We never reference compile time classes/interfaces in our API (in Value/Style annotations etc) as it's unreliable and can lead to problems, the only exception to this is probably annotation classes, but most of the time it's just a convenience to pass verified FQCN of annotation, we don't load these classes during annotation processing, we only use so called "mirrors" to operate on them. In order to provide user-level extendable compilation customization we need to use something like https://immutables.github.io/encoding.html but not for an attribute, but to encode a number of attributes in  `toString`, `hashCode`, `equals` etc, which is not implemented, will further require some R&D and some templating/api handles to understand properties of otherwise opaque attributes (like if it's primitive, optional or not, collection etc, I dunno what else might be useful for `toString` implementors). Yet another approach could be establishing annotation processor plugins to be loaded into annotation processor via say META-INF or FQCN (with class refs, as I mentioned this can be problematic depending on how it is actually done), in any way sort of API/template handles are have to be provided so that custom code injector can understand what it works with (list of attributes at minimum, see above).

**Comment by mickroll** [comment]
Yes, creating a plugin mechanism would add a lot of complexity. That's why I see the current solution with minimum complexity as the best way. 👍
