### ISSUE TITLE
null checks should throw IllegalArgumentException instead of NullPointerException

### ISSUE THREAD

**Issue by haroldcarr** [immutables/immutables#124]
Immutables generates code like:

    public final Builder withId(String id) {
        this.id = Preconditions.checkNotNull(id);
        ...

checkNotNull throws NullPointerException if 'id' is null.

It would be useful to have a customization that enables IllegalArgumentException to be thrown instead.

**Comment by elucash** [comment]
Hi Harold
I imagine that this kind customization could be useful for some cases.

There are many different interpretation how one could think about using IAE or NPE for this case (http://stackoverflow.com/questions/3881/illegalargumentexception-or-nullpointerexception-for-a-null-parameter thread present some arguments on this)
I would not use Guava or other third party library as example, but if you take IMO most relevant parts of JDK libraries such as lang, collections, concurrent, then you'll see that NPE used for null parameter check.

In past I've used to use `IllegalArgumentException` of even use `NullPointerException` and wrap it in `IllegalArgumentException` before throwing, and I've seen some people subclass `NullArgumentException extends IllegalArgumentException` for that. But what I should to admit is that this choice had no practical implications in that sense that if I would use plain `RuntimeException` for this, that would not change surrounding code/diagnostic code that much; would it?

If we have this implemented and code like `Preconditions.checkArgument(arg != null)` would be generated, you will still might have some `NullPointerException` coming from Java Collection Framework and Guava used underneath. This is the problem (probably a minor one) with having a convention which doesn't match the one in JDK classes.

Currently I'm 40% - for, 60% - against adding this customization. Mostly because I found it bring low amount of value added rather than strong opinion on that.
wdyt? Are there compelling benefits of having this, how it will make life easier in a practical sense rather than "it's right convention to use [for a given codebase]"?

/cc @augustotravillio

**Comment by haroldcarr** [comment]
I apologize for the delay.

When I see NPE I think the program is broke in the sense that an algorithm has been coded incorrectly.

When I see IAE I think that some data in the program is not meeting its requirements.

No big deal, but IAE just seems more "correct" in this case.

I can close the issue if you prefer not to change the current behavior.

Thanks,
H

**Comment by elucash** [comment]
Current default behavior will stick to NPE. Not because it's more correct, but mostly because of conformance to JDK convention (briefly expresses in _Effective Java 2nd ed, Item 60_).
What we can consider to improve on the current state:

* Add messages for parameter checks. Having messages with parameters named will add better diagnostic, will look less like arbitrary null pointer dereference.
* Add style to generate IAE check instead of NPE check. This style will be disabled by default.

**Comment by elucash** [comment]
While we are not adding styles for that, but there's new option to make this possible by using import rewrite extension (see #171). Using it it's possible to rewrite `Objects.requireNonNull` to some custom package, where implementation would throw needed exception type. Thank you!

**Comment by haroldcarr** [comment]
+1
