### ISSUE TITLE
Consider using Java requireNonNull instead of Guava checkNotNull in generated code

### ISSUE THREAD

**Issue by andrewgaul** [immutables/immutables#129]
`checkNotNull` triggers Modernizer violations in generated code: andrewgaul/modernizer-maven-plugin#28.  Immutables already requires Java 7 so generated code can use `requireNonNull`.

**Comment by elucash** [comment]
Thank you for reporting the issue!
Immutables able to generate JDK only code, including mentioned `requireNonNull`. In order to do this either of the following should be true:

* There is no Guava on the class-path
* Or set style `@Value.Style(jdkOnly = true, ...)` . (see [guide](http://immutables.github.io/style.html) on how to apply styles)

Please check if you can apply any of the above.
If there need to mostly use Guava in generated code as it is, but to have `requireNonNull` or other goodies to replace guava's, then we could discuss complete set of API or other workarounds.

**Comment by andrewgaul** [comment]
@talios Does using JDK-only code address your issue?

**Comment by talios** [comment]
@andrewgaul Just noticed this - is that a new setting or has it been there for awhile? Seems to work a treat cheers!

**Comment by elucash** [comment]
it's one of the main new features in 2.0: Guava is no longer a required dependency, albeit still fully supported if present. `jdkOnly` setting is to force usage of JDK only utilities as classpath may just contain Guava even if you don't want to use it in a generated code (and still if you use explicit ImmutableList from guava, for example, it should work as expected).
