### ISSUE TITLE
Usage of Abstract Classes vs Interfaces for Immutables

### ISSUE THREAD

**Issue by overfullstack** [immutables/immutables#1299]
I see in the examples given [here](https://immutables.github.io/immutable.html) some examples has abstract classes, while others have interfaces used. What's the significance of each? (Sorry if I missed, but I couldn't find when to use what in the documentation, AFAIU from my experimentation, I am able to interchange them)

**Comment by elucash** [comment]
Use what suites your needs. Interfaces as abstract value types allows for relatively clutter free definitions on the high level of abstraction: interfaces allows for a kind of multiple inheritance and simpler mocking (whether it's good or bad, probably bad IMHO for value types), no need to type `public abstract` and you can use default methods since java 8 (Immutables was initially originally for java 6-7, then updated for 8 and up). Abstract classes restrict to a single inheritance, can have non-abstract methods for default/derived lazy attributes and regular methods (and these methods sometimes cannot be expressed as default methods in interfaces: customizing/overriding `toString`, `equals` or `hashCode` is not possible for interface definitions), and for some obscure usages when you might need to define no-arg empty constructor to limit inheritance visibility (protected or package-private) or place some magic annotation that some framework might require. What I think most users can do is start using interfaces for brevity and switch to abstract classes where required. On the other end of spectrum some might prefer to restrict codebase to only abstract classes definitions (for value types) for extra consistency and accepting both restrictions of classes with power of defining regular methods etc.

**Comment by overfullstack** [comment]
Thanks, @elucash for a detailed explanation. I got the point!
