### ISSUE TITLE
More Javadoc inheriting

### ISSUE THREAD

**Issue by pushbit** [immutables/immutables#131]
How feasible would it be to inherit more Javadoc attributes from the abstract class?  For example, if I include class or method tags like `@since` or `@deprecated`, those should be included in the generated class.

Also, if an abstract method includes a `@return` tag, the value in the generated class should be `{@inheritDoc}` instead of the current default, "value of foo attribute".  And it would be nice if we could somehow disable the `@return` tag since I usually don't include one when it's either obvious from the method name or the Javadoc already explains what is returned.

**Comment by elucash** [comment]
Played with it for a while, I guess there are some improvements.

Logic is as follows

* if implementation class is public and abstract value type has accessor's javadoc
  + javadoc will be copied to the implementation accessors, including `@since`, `@deprecated`. 
  + not adding anything else, well-formedness fully depends on original javadoc
* otherwise default javadoc will be added: simply `@return` with message as it was before, but without `{@inheritDoc}` as there's apparently nothing to inherit.
* transitive javadoc inheritance is not processed (too sophisticated to be practical to implement vs value it brings)

You can evaluate `2.1.0-SNAPSHOT` from sonatype oss repository

```
<!-- sample sonatype repository -->
<repositories>
    <repository>
      <id>sonatype-nexus-snapshots</id>
      <name>Sonatype Nexus Snapshots</name>
      <url>https://oss.sonatype.org/content/repositories/snapshots</url>
      <releases>
        <enabled>false</enabled>
      </releases>
      <snapshots>
        <enabled>true</enabled>
      </snapshots>
    </repository>
  </repositories>
```
or build yourself from this git repository.

**Comment by pushbit** [comment]
Working nicely, thanks!
