### ISSUE TITLE
Customize the @Nullable annotation in generated code

### ISSUE THREAD

**Issue by erdinc-gopuff** [immutables/immutables#1311]
I have some Optional fields on my types and code generated by Immutables puts javax.annotation.Nullable annotation on these fields. We are using the micronaut.io framework and the framework's annotation processor complains that we aren't using their io.micronaut.core.annotation.Nullable annotation but using javax.annotation.Nullable instead. So my question is, is it possible to configure immutables to generate code that uses a different Nullable annotation than javax.annotation.Nullable? Or can we simply configure it to not put any Nullable annotations in generated code at all?

Thanks!

**Comment by elucash** [comment]
Usually we just copy nullable annotation if it specified, but for other cases like this one we just assume `javax.annotation.Nullable` if it's found on the classpath. In your case I assume you have it on a compilation classpath (because of the usual jar-hell situation) but don't want it (because of Micronaut, which could have also ignored it but complain instead). The "simple" way is to hide this annotation from discovery either using whitelist or blacklist: please read the javadoc of `Value.Style.allowedClasspathAnnotations` and consider `META-INF/extensions/org.immutables.inhibit-classpath`  mentioned there too (see also #740).
That being said, we anticipate many people would try to use `Nullable` annotation that is not `javax.annotation.Nullable` (which is now considered part of JEE-something or for whatever other reason). So I'm about to add additional style flag (`Style.fallbackNullableAnnotation`) to specify Nullable annotation to use when there is no original nullable annotation known.

**Comment by elucash** [comment]
The new `Style.fallbackNullableAnnotation` released in `2.9.0-beta3`

**Comment by erdinc-gopuff** [comment]
Awesome thank you!

**Comment by erdinc-gopuff** [comment]
I am using a gradle build, and I created a src/main/resources/META-INF/extensions/org.immutables.inhibit-classpath file with 
javax.annotation.Nullable as it's value. For some reason, immutables isn't picking it up still. What am I doing wrong?

**Comment by elucash** [comment]
oh, cannot say for sure, not actively using gradle, but you can try to add `META-INF/extensions/org.immutables.inhibit-classpath` to the both compile and annotation-processor classpath, this will increase chances annotation processor will actually sees it.
