### ISSUE TITLE
@InjectAnnotation with @Inject Does Not Annotate Constructor

### ISSUE THREAD

**Issue by rtatton** [immutables/immutables#1316]
## Dependencies
- org.immutables:value:2.8.8
- org.immutables:annotate:2.8.8

## Notes
I know that the `@ImmutableInject` annotation below works with at least `Where.FIELD`, `Where.SYNTHETIC_FIELD`, and `Where.METHOD`. However, according to the [`javax.inject.Inject`](https://docs.oracle.com/javaee/7/api/javax/inject/Inject.html) documentation, injecting on fields is not an option since they cannot be marked `final`. I have seen issues [#317](https://github.com/immutables/immutables/issues/317) and #396, but have not had any luck.

## Example code
```
// ImmutableInject.java
 
package example

import javax.inject.Inject;
import org.immutables.annotate.InjectAnnotation;
import org.immutables.annotate.InjectAnnotation.Where;

@InjectAnnotation(type = Inject.class, target = {Where.CONSTRUCTOR})
public @interface ImmutableInject {}
```

```
// ImmutableStyle.java

package example

@Target({ElementType.PACKAGE, ElementType.TYPE})
@Retention(RetentionPolicy.CLASS)
@Value.Style(
    get = {"is*", "get*"},
    init = "set*",
    strictBuilder = true,
    builder = "newBuilder",
    typeAbstract = "*",
    deepImmutablesDetection = true,
    depluralize = true,
    visibility = ImplementationVisibility.PACKAGE,
    defaults = @Value.Immutable(prehash = true))
public @interface ImmutableStyle {}
```

```
// package-info.java

@ImmutableStyle
package example
```

```
package example

@Value.Immutable
@ImmutableInject
public abstract class Example{
    ...
}
```

**Comment by rtatton** [comment]
Update: It works when `@Value.Style` includes `of = "new", allParameters = true`. This is good enough. However, it would be ideal to be able to add the annotation to a non-public constructor that still contains all the parameters. `javax.inject.Inject` supports this, but I am unsure what complexity this would add to the `@InjectAnnotation` implementation.

**Comment by elucash** [comment]
Private constructor is not guaranteed to have specific shape, and we have about 3-4 strategies to generate constructor, using copy parameters, receiving builder arg or variations of these. As a matter of fact, by using  `of = "new", allParameters = true` you would actually instruct Immutables to generate specific "official" constructor receiving all attributes as parameters and that's why it works and, in my view, is quite legitimate way to achieve what is needed here.
There's, of course, unclear why there's a need to use immutable object as a mutable one by injecting fields after construction etc. I would just stick to regular objects with package-private non-final `@Inject` fields in this case. There's an option to use `@Value.Modifiable` too, it will have non-final fields generated, setters etc, but it may be more cumbersome than just do `of = "new", allParameters=true` if that works.

**Comment by rtatton** [comment]
Hey @elucash. Thank you for the prompt clarification. That is a very good point regarding the multiple private constructors. In my use case, I am still treating the object as immutable by injecting on the constructor, rather than the fields, so those are still marked with `final`. While there is flexibility to using a POJO for dependency injection, Immutables is incredibly beneficial for writing boilerplate, among its many other advanced functionalities, besides the safety (and sanity) benefits of having immutable objects.

**Comment by rtatton** [comment]
The only benefit to be had with allowing the `@Inject` on a non-public constructor is to prevent classes even within the same package from seeing this extra constructor.
