### ISSUE TITLE
Builder re-use, clear method

### ISSUE THREAD

**Issue by pushbit** [immutables/immutables#138]
In order to more easily re-use builders for building multiple instances, it would be nice if there was a way to reset all of the fields to their uninitialised values (null/0/false/empty array/collection).  This would help in the case where a varying subset of the fields are being set for each instance.  It could possibly be a `clear` method or a `copy` method that accepts a source Builder and copies all of the field values to the target instance (similar to what we're discussing for `@Modifiable` in #130).

**Comment by elucash** [comment]
Hi, currently, I'm trying to figure out if it's already possible or we had to add something new for this.
By default you have non-strict builders are being generated. Non-strict builders can initialize attributes multiple times and reset collections to needed state, including making collections empty. In addition there's `from` method which can merge attribute values from provided sample instance into the builder.

Another idea is that if you need more flexibility, like querying which attributes was set, to what value, then there will be mentioned `@Modifiable` class generated, which will in turn serve as advanced builder of some form, because we will have `toImmutable()` to convert instance to immutable state. This can actually add more motivation to have better reset on _modifiable_ instance. So instead of having `copyFrom`/`mergeFrom` variations of copy methods, those could be replaced with pair of `reset`(or `clear`) and `from` (as in merge), so if you will want to merge (mix and add) values from a sample instance, we could call `modifiableInstance.from(sampleInstance)`, but if we need overrided (not merge collections for example), we would use `modifiableInstance.reset().from(sampleInstance)`

**Comment by pushbit** [comment]
I tried to review all of the existing Builder methods and options, but I didn't see anything that would reset all of the fields to their initial values (as if the Builder was just instantiated).  Of course this could be done manually, but with Builders with 20+ fields the client code would get quite long and messy compared to just calling a `reset` method.

I like your idea for `reset` and `from` methods in `@Modifiable`.  And I think it would be great to also have these methods in Builders for the cases (most of mine so far) where we only want to generate an `@Immutable` with a re-usable Builder.

**Comment by elucash** [comment]
See [`@Value.Modifiable`](https://github.com/immutables/immutables/blob/master/value/src/org/immutables/value/Value.java#L328) annotation javadoc for the details. To be mentioned in documentation

**Comment by pushbit** [comment]
Can we revisit this idea of having a `Builder.clear` method?  My goal is to have one builder instance which builds many `Immutable*` instances, each with varying fields set.

I looked at two existing possibilities.  `Builder.from` is not suitable because it only copies non-null values and it doesn't clear collections.  `Modifiable*.toImmutable` also doesn't meet the requirements because it creates a new `Builder` instance each time it is called.  I'm working in a memory sensitive environment and need to limit object creation and GC as much as possible.

I think that if `Builder` had a `clear` method, just like `Modifiable*`, it would solve this issue.

**Comment by elucash** [comment]
I'll see how we can fix it

**Comment by elucash** [comment]
Clear method on builder will be generated when turned on using style `Value.Style(clearBuilder = true)`.
When using jdk-only collections, they will be cleared `.clear()`, if using guava immutable collections, new builders will be created instead. With non-collection attributes everything is simple.

**Comment by elucash** [comment]
Released in 2.1.0
