### ISSUE TITLE
Default attributes initialisation order

### ISSUE THREAD

**Issue by vst** [immutables/immutables#140]
From the documentation about [default attributes](https://immutables.github.io/immutable.html#default-attributes):

> Default attribute method's body should not refer to any other derived or default attribute. Otherwise construction will be broken due to unspecified initialization order. It's only guaranteed that all attributes with abstract accessors will be initialized before default and derived attributes, and therefore could be safely referred in initializers.

I am trying to default a @Default based on another @Default.

When I checked the generated source code, I saw that attributes are initialised in the same order as I defined them in my immutable value class. So it is not necessarily *unspecified*.

1. I need this functionality and believe that the lack of support for such cases is counter-intuitive.
2. It should not only be possible but also transparent, like defining the initialisation priorities specified in the @Default annotation.

**Comment by augustotravillio** [comment]
We choose to not rely on any specific ordering of default/derived attributes as it is hard to make guarantees as attribute initializers could call each other, or when new default/derived attribute is being added in the source code and subtly breaks initialization ordering. Reliable implementation would actually track which attributes was set during construction and also detect cycles in initialization by throwing exception. So let's get that proper implementation!

Thank you for the feature request!

**Comment by elucash** [comment]
There was also issues with Eclipse compiler ignored source definition ordering, this has since being fixed in ECJ and hacked in _Immutables_, but historically we avoid to rely on ordering where possible. I like the idea to get rid of this limitation.

At first I thought that we bring to much overhead by having fields to track state, anyway, we have lazy attributes with reasonably complex implementation and some overhead already, then if you want no overhead, just make those attributes mandatory and pre-calculate manually — seems like a natural trade off as correctness more important here.

**Comment by elucash** [comment]
Released in 2.1.0
