### ISSUE TITLE
Question about customizing the generator

### ISSUE THREAD

**Issue by cameronprater** [immutables/immutables#1448]
I'm continuing work on my fork of Immutables for my project (I plan to build something from the ground up later on that I can customize to better suit my needs). I want to enable the copying of Immutables-annotated types' inner types to the generated class when an annotation is present. 

For example, the following abstract type:
```java
@Value.Immutable
abstract class Foo {

  @Value.Copied // the new annotation  
   enum Type {
     ...
  }
}
```

would generate this immutable type:
```java
class ImmutableFoo {

  // the annotated type is copied exactly, but the annotation is removed
   enum Type {
     ...
  }
}
```

My current understanding of enabling this in the generator would be around here towards the beginning of `Immutables.generator`:
```
    [if type.constitution.hasEnclosingNonvalue]
[-- Enclosing non-value type --]
[output.java type.package type.typeEnclosing.simple type.element]
[generateEnclosing type]
[/output.java]
    [/if]
```

where I would modify `Constitution.hasEnclosingNonvalue()` to check for the existence of the `@Value.Copied` annotation, and create another template to copy the target type, where the template would look something like:
```
[template generateCopy Type type]
[packageWhenTopLevel type true]

[annotationsWhenTopLevel type true]
// ... ?

[/template]
```

However, I'm not sure how to leverage Immutables API to create the template I need.  Ideally, everything would be copied from the annotated type except for the `@Value.Copied` annotation (Javadoc, other annotations, visibility, members, etc.). Is there a mechanism to just copy the source code exactly? Otherwise, are you able to point me in the right direction? I don't want to get too in the weeds of the generator code because I don't really understand it. My specific use case only involves copying enums. Thanks

**Comment by elucash** [comment]
Hi! I can try to find some time later this week (just ping me on one of the issues) to try to explain some of the details/give some pointers. Now I can give you only brief points

* `hasEnclosingNonvalue` and the associated concept is quite specific, so you probably will save time/energy by not messing with it
* We can find better, cleaner place to insert new template
* Writing template, albeit a bit arcane, is quite easy, that is not a problem
* Annotation processors (in general) have no access to the source code, only to reflection-like compile time model of the types and other language elements, so you'll have to analyze your way through which would be nightmare for each non-trivial cases.
  * However Immutables have certain routines which retrieve the source code in compile specific ways. Due to differences in compilers (Javac vs ECJ) in one of those (I don't remember which one) you don't know the range associated with the particular element and might need to parse your way through (as we did for attribute name ordering and for Encodings functionality). Can be quite challenging too.
* 98% chance we will launch Immutables 3 development soon, which will be all around extensibility: solid and extensible model, will discontinue templates (they are as complicated as code now, oftentimes even more), but there will be other mechanisms for composing code/adding own templates, overall this will make certain tasks like read -> transform -> write code a lot easier, so I expect to learn from the use-cases like yours

**Comment by cameronprater** [comment]
Thanks for the response! Noted, I will not mess with `hasEnclosingNonvalue` and will wait for your further pointers.
From my very brief look into annotation processing, I believe you can access some of the source code using `Trees` API but I was not sure whether Immutables leveraged this anywhere and was not sure whether what is accessible from `Trees` is useful or not.

Extensibility is the one thing I wish there was more of in Immutables currently (encodings are nice for type-specific implementation, but specific generator/abstract type customization isn't solved by this, and also can't generate additional "with" methods like `withAdditionalFoo` for collection elements, which is the main feature I am using rather than builders) so I'm looking definitely looking forward to Immutables 3.

**Comment by cameronprater** [comment]
Hi @elucash, when you have a moment, where do you think the best place to put this template would be and which mechanisms can I leverage to generate the copied enums? If it helps, my use case only involves copying Enums, and some of them are located in nested Immutables (e.g. an Immutables abstract type enclosed in an `@Enclosing` immutable). I know I can solve this issue by relocating the enums outside the abstract types, but I prefer they be nested inside the generated Immutables themselves.

**Comment by elucash** [comment]
will get back to it in a couple of hours, I'll provide pointers / an example for this usecase

**Comment by elucash** [comment]
So to start to deliver on the promises, here's first thing: I you use and enclosing namespacing, then the entry point would be 
in `Immutables.generator`

```
101|[annotationsWhenTopLevel type true]
102|[type.typeEnclosing.access]final class [type.typeEnclosing.simple] {
103|  private [type.typeEnclosing.simple]() {}
104|  [--start adding here --]
```

that's basically the whole idea, start with some entry point, and call a template from there
```
[template x]
[/template]
```

then call it like
```
[x]
```

You will need to tap into the data you need. You can start with adding some accessor to the `ValueType`. Let me know if this is helping you. I'll adjust based on the feedback

**Comment by cameronprater** [comment]
Thanks so much! I've seemed to have gotten it generating properly, except I have a problem.

I can't implement the logic in the template to decide when to print a `,` or a `;` after the enum. I attempted to leverage the `for.index` property in an `if` statement to decide like so:
```
[for c in e.constants]
[c]([e.type].[c])[if for.index eq size e.constants];[else],[/if]
[/for]
```

However, the `if` always evaluates as true and prints a `;`, like so:
```java
  public enum Type {
    UNKNOWN(InteractionJson.Type.UNKNOWN);
    PING(InteractionJson.Type.PING);
    APPLICATION_COMMAND(InteractionJson.Type.APPLICATION_COMMAND);
    MESSAGE_COMPONENT(InteractionJson.Type.MESSAGE_COMPONENT);
    APPLICATION_COMMAND_AUTOCOMPLETE(InteractionJson.Type.APPLICATION_COMMAND_AUTOCOMPLETE);
    MODAL_SUBMIT(InteractionJson.Type.MODAL_SUBMIT);

    // fields, constructor, methods...
}
```

 I can't seem to think of another way to implement this logic in the template.

**Comment by elucash** [comment]
Yep, I decided to not implement smth like `for.last`, there were technical difficulties with this (due to syntax `[for a in b, c in a if a.u ]` etc). So from the top of my head

1. Try something like you do, but with parens
`[if for.index eq (len e.constants)]`
2. You can rearrange the loop so you do `if not for.first` for comma and put semicolon after the loop, notice the intentional whitespace handling

```
[for c in e.constants][if not for.first],[/if]
[c]([e.type].[c])[/for];

```

**Comment by cameronprater** [comment]
Yes, both methods seem to have worked :) I wasn't sure how order of operations were applied to evaluate the expression, but I prefer your approach without an extra built-in function, thanks for all the help!
