### ISSUE TITLE
With* Interface not always generated

### ISSUE THREAD

**Issue by dylanbaroody** [immutables/immutables#1469]
Hello!

We are seeing an issue where sometimes the `WithValueObject` is generated, and sometimes, it is not.

For example:

```java
@Immutable
get = {"is*", "get*", "has*"},
    init = "set*",
    newBuilder = "builder",
    optionalAcceptNullable = true,
    forceJacksonPropertyNames = false,
    visibility = ImplementationVisibility.SAME,
    depluralize = true,
    allParameters = true,
    strictBuilder = true,
    jdkOnly = true,
    throwForInvalidImmutableState = InvalidImmutableStateException.class
@JsonSerialize(as = ImmutableValueObject.class)
@JsonDeserialize(as = ImmutableValueObject.class)
public interface ValueObject extends WithValueObject {
}
```

This compiles sometimes, and other times it does not, claiming it cannot find `WithValueObject`

**Comment by elucash** [comment]
build tool? (or IDE?) incremental?

**Comment by dylanbaroody** [comment]
This is using maven, with compiler plugin 3.8.0

**Comment by elucash** [comment]
just in case, have you tried disable incremental compilation?

```xml
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>...</version>
  <configuration>
    ....
    <useIncrementalCompilation>false</useIncrementalCompilation>
  </configuration>

**Comment by dylanbaroody** [comment]
Turning off incremental compilation does seem to solve the problem, however this reference from maven gives me pause:

```
false (not recommended) this only compiles source files which are newer than their corresponding class files, namely which have changed since the last compilation. This does not recompile other classes which use the changed class, potentially leaving them with references to methods that no longer exist, leading to errors at runtime.
```

Why does turning it off help with this issue?

**Comment by elucash** [comment]
my theory is that particular (maven-plugin/javac combo?) incremental compilation scheme does screw up with annotation processing environment and rounds of compilations. Wild guess - newly generated files are not getting in the classpath of originally incrementally recompiled class which have no chance to attempt to compile against regeneratew With classes, but newly generated classes are compiled on some sort of isolated round. Unfortunately, so far I don't see a solution on our side. It's safer to not use not-yet-generated types, at least in signatures of classes / methods / fields, but often this defeats the purpose. One can generate "With" once and move it into the codebase (because it's interface, it's not that ugly). I dunno, or resort to disabling incremental mode, I'm used to do "clean install" in Maven for decades now (I enjoy incremental compilation with other tools)

**Comment by dylanbaroody** [comment]
Ok - thank you!
