### ISSUE TITLE
Put auto-singleton feature under feature flag (disabled by default)

### ISSUE THREAD

**Issue by augustotravillio** [immutables/immutables#147]
Now:
- Hard to reason about when singleton/default instance will be generated
- Complicates generated code and annotation processing for no much benefit.
- No way to force separate, non-singleton instances when there's no settable attributes.

Should be:
+ use only explicit singletons when `singleton=true`

Compatibility will be probably broken a bit, but it is expected that almost no people use it on purpose.
Will document this change in 2.1.

**Comment by elucash** [comment]
I would support this, we got rid of automatic `prehash` enabling in the same manner. Need to be careful though. Logic there is fragile enough, at least need to add more compilation/unit tests for this.

**Comment by jbergfi** [comment]
I've been using this "accidental" feature in 2.0.13 quite a bit for simple Immutables that don't contain any fields. Today I tested 2.0.21 because I wanted the no-arg constructor to use in kryo deserialization but I lost the auto-singleton of() method. I have quite a bunch of these Immutables and I would want to be able to put the singleton generation as a flag on the package (so I don't need to clutter it on each abstract class). I tried to put this style on the whole package:

@Target({ElementType.PACKAGE, ElementType.TYPE})
@Retention(RetentionPolicy.CLASS) // Make it class retention for incremental compilation
@Value.Style(
		typeAbstract = {"Abstract*"},
		typeImmutable = "*",
		visibility = ImplementationVisibility.PUBLIC,
		allParameters = true,
		privateNoargConstructor = true
		defaults = @Value.Immutable(singleton=true)
)

But this doesn't work since it will try to make singletons out of classes with mandatory fields as well. Best would be if it could detect that there are mandatory fields and not try to generate any singleton then (but still create the no-arg constructor in my case since I have privateNoargConstructor = true).

In eclipse this problem appears as compilation error on primitives being assigned null (error message from javac is more clear).

Regardless of the singleton feature I would still want to see the of() method generated since I have set allParameters = true which generates of-methods for all other Immutables.

I could workaround these problems of setting "@Immutable(singleton=true)" on each and every simple Immutable I have, I guess, but I would rather wait if it will be possible to put it on the whole package in some not-too-distant release.

**Comment by elucash** [comment]
In the course of action we're reverting original change, but adding feature flag `Style.attributelessSingleton` which will be `false` by default in 2.1. This way we can preserve old behavior when needed even if don't want to have it by default.

**Comment by elucash** [comment]
Released in 2.1.0
