### ISSUE TITLE
Switch from Optional.of to Optional.ofNullable

### ISSUE THREAD

**Issue by ldriscoll** [immutables/immutables#152]
When we have `java.util.Optional<T>` fields, it would be nice that the `withX` methods could handle `null`, and use `java.util.Optional.ofNullable(x)` instead of `java.util.Optional.of(x)`

**Comment by augustotravillio** [comment]
Hi Luke, thank you for suggestion! There's a point that it's probably better to not mask nulls making transition explicit:  `withX(Optional.ofNullable(x))`. But since it's being asked quite often, think we should make special style switch like `@Value.Style(optionalAcceptNullable=true..` to make this possible. It will not be the default, however styles are [flexible enough](http://immutables.github.io/style.html#apply-style) to enable globally for a codebase.

**Comment by ldriscoll** [comment]
sounds good, I'll take a crack at it if that helps?

**Comment by augustotravillio** [comment]
Added `@Nullable` and cosmetic change to templates, in some places we also have null handled by other means, just removed the check

**Comment by elucash** [comment]
released in 2.0.18, thanks!

**Comment by ldriscoll** [comment]
awesome, thanks.
