### ISSUE TITLE
generate builder factory method with extended builder

### ISSUE THREAD

**Issue by squiddle** [immutables/immutables#166]
I want to add convenience methods to the builder for easier construction.

```java
@Value.Immutable
public interface Link {
    public URI getHref();
    public class Builder extends ImmutableLink.Builder {
         public Builder href(String s) {
             return (Builder) href(URI.create(s));
         }
    }
}
```

This works so far, but it does not generate the `ImmutableLink.builder()` method anymore. So i have to use `new Link.Builder()` instead. 

The return value for the default builder methods adapts to the extended builder.

Why cant the static factory method for the builder still be created?

**Comment by elucash** [comment]
Than you for reporting the issue. While extending Builders you can add constructors with parameters, so in order to generate proper builder method there need to be an analysis of such constructors/parameters, currently I think it would be too much for such trivial cases. I could recommend following alternatives:

1. Define builder factory in abstract value type
```java
@Value.Immutable
public interface Link {
    public URI getHref();
    // works in java 8, for java 7 you need to resort to using abstract class instead of interface
    public static Builder builder() { 
       return new Builder();
    }
    public class Builder extends ImmutableLink.Builder {
         public Builder href(String s) {
             return (Builder) href(URI.create(s));
         }
    }
}
```
Notice the more concise invocation  `Link.builder()` instead of `ImmutableLink.builder()`

2. Use reverse extension where generated builder would extend manually written one and use abstract methods to call generated initializers.
```java
@Value.Immutable
public interface Link {
	public URI getHref();
	public static abstract class Builder {
		public ImmutableLink.Builder href(String s) {
			return href(URI.create(s));
		}
		abstract ImmutableLink.Builder href(URI create);
	}
}
```
Notice that we are returning generated type `ImmutableLink.Builder`  instead of just `Builder`
