### ISSUE TITLE
Deepcopy of Map<String, Set<String>>

### ISSUE THREAD

**Issue by qinfchen** [immutables/immutables#173]
Hi, 

I noticed Immutables don't do a deep copy of `Map<String, Set<String>>`, the set is still modifiable via the original reference.  Here is a unit test to verify that, the second assertEquals should fail but it passes.

```java
        Map<String, Set<String>> maps = new HashMap<>();
        Set<String> values = new HashSet<>(Arrays.asList("fakeValue1"));
        maps.put("someKey", values);
        ImmutableThing thing = Thing.builder()
                .setMaps(maps)
                .build();
        assertEquals(maps, thing.getMaps());
        values.add("fakeValue2");
        assertEquals(maps, thing.getMaps());
```

**Comment by elucash** [comment]
Thank you for the issue report! However strange it may sound, but this is expected behavior, we basically mimic what `ImmutableMap.copyOf` and other immutable collections are doing. While it is possible to implement this by analyzing and detecting nested collection types, but we are not ready to do this yet due to more complex analysis and change of semantic.
From the practical point of view, I would suggest to do conversion explicitly or use specialized collection types if suitable.

Explicit conversion

```java
 Map<String, Set<String>> maps = new HashMap<>();
        Set<String> values = new HashSet<>(Arrays.asList("fakeValue1"));
        maps.put("someKey", values);
        
        ImmutableThing thing = Thing.builder()
                .setMaps(Maps.transformValues(maps, ImmutableSet::copyOf))
                .build();
```

Specialized collection: a lot of uses of collections in collections could be replaced with `Multimap<K, V>` (see also `(Immutable)Table<C, R, V>`, which is not supported specifically, but also works as plain attribute)

```java
Multimap<String, String> multimap = HashMultimap.create();
multimap.put("someKey", "fakeValue1");

        ImmutableThing thing = Thing.builder()
                .setMultimap(multimap)
                .build();
```

**Comment by qinfchen** [comment]
Cool. Thanks for the reply. I will keep this ticket open for now, but please feel free to close it.
