### ISSUE TITLE
Optional collections

### ISSUE THREAD

**Issue by a1russell** [immutables/immutables#181]
Immutables has great support for both optional values and collections, but I'd love to see, as an enhancement, support for both combined. I have a use case where I'm representing a nested JSON structure using serializable Immutables, and some of the attributes that would be lists are optional.

It would be nice if an attribute `foo` was, say, an `Optional<ImmutableList<T>>`, we got these methods:

`foo(Iterable<? extends T>)`
`foo(Optional<Iterable<? extends T>>)`
`addFoo(T)`
`addFoo(T...)`
`addAllFoo(Iterable<? extends T>)`

**Comment by elucash** [comment]
Thank you for the feature request. Something similar was raised some time ago so we already have an opinion on that. I think that that particular combination is complicated to define and use and, probably, unnecessary complicated. If you really need optional of collection then it's not a big deal to create collection without generated convenience methods

```java
builder.foo(ImmutableList.<T>builder()
    .add(t1)
    .add(t2)
    .build());
```

Otherwise, empty collection could serve as absent.
If you have to deal with JSON, then there are options available. For GSON you should use `@Gson.TypeAdapters(emptyAsNulls = true)` and then make sure `serializeNulls()` is _not_ called on gson builder or set on `JsonWriter`.
For Jackson there are annotations like `@JsonSerialize(include=JsonSerialize.Inclusion.NON_EMPTY)` or `@JsonInclude` similar to that (http://stackoverflow.com/questions/16089651/jackson-serialization-ignore-empty-values-or-null). If some of the jackson annotations are not propagated properly to a generated class you can try to use `Value.Style(additionalJsonAnnotations = {JsonInclude.class,...})` to list addition annotations if they are not propagated by default.

**Comment by a1russell** [comment]
Thanks for the points @elucash! I realize that I can use the ImmutableList.builder, but I did not find it quite as nice as it could be if there were convenience methods.

I was going to ask for the older issue where this was raised (I did search before creating this one), but now that I think about it a little more closely, I think I know why you don't want to do it. You don't want to answer the question of what should happen after something like `builder.foo(Optional.empty()).addFoo(t1).build()`. Do you add to the None (sorry, borrowing Scala terms) or replace it with Some new list builder?

**Comment by elucash** [comment]
We had an idea to implement it with the same motivation [JSON], discussed it internally, tried couple of API examples and found out that it's just not work very well together and other alternatives are simpler. The example you provided is another nice illustration of complication we could run to if implement this functionality. Thank you for consideration and hope other options will work for you! Feel free to ask questions on mailing list or report other features/bug here, on the issues tracker.

**Comment by a1russell** [comment]
Thanks for the elaboration! :smile:
