### ISSUE TITLE
Generate public constructor

### ISSUE THREAD

**Issue by jroper** [immutables/immutables#231]
Jackson support could be even nicer than it currently is, using Jacksons JDK8 named parameter module - you could have Jackson support without adding any Jackson annotations to the class whatsoever.  However, this would require the generation of a public constructor, rather than (or in addition to) the `of` constructor method.

**Comment by elucash** [comment]
As of version 2.1.5 (just released) you can use naming template for `of` constructor method to use special value `"new"` (similar to a `builder` method) which will produce a public constructor instead of a factory method.

```java
@Value.Style(of = "new")
public interface Constr {

  @Value.Immutable
  public interface Rev {
    @Value.Parameter
    int major();

    @Value.Parameter
    int minor();
  }

  @Value.Immutable
  public interface Build {
    @Value.Parameter
    String date();

    @Value.Parameter
    String qualifier();
  }

  static void use() {
    new ImRev(1, 2);
    new ImBuild("2016.01.01", "Happy new build!");
  }
}
```

To turn all attributes into constructor parameters automatically without explicit `@Parameter` annotation, please, use `allParameters` style as shown in http://immutables.github.io/immutable.html#tuples

I would not advertise this as Jackson-ready solution, but I hope this will be enough to support the use case.
Thank you for suggestion!

**Comment by mihbor** [comment]
Trying to generate the public constructor as per the above with the following style annotation:
`@Value.Style(typeImmutable="*Impl", allParameters=true, of="new")
`
Instead it generates the following static (un-compilable) creator method:

```
  public static EndTurnImpl new(String playerId, long turn) {
    return new EndTurnImpl(playerId, turn);
  }
```

Tried both 2.1.5 and the latest (2.3)

**Comment by mihbor** [comment]
Strangely, it started generating the public constructor correctly after restarting my IDE, so please ignore my above comment.

**Comment by elucash** [comment]
@mihbor maybe it's related to aggressive caching, it is known that style changes might not apply correctly right away in IDEs
