### ISSUE TITLE
Add annotation in the immutable object ?

### ISSUE THREAD

**Issue by oroger** [immutables/immutables#265]
I recently discovered the immutables.org project and I really do like it.

However, I am currently stuck for a specific use case: I would like to generate an immutable class that does contains a specific annotation: @XmlRootElement. That annotation is not inherited (via @Inherited) so even if the generated class extends the abstract definition, it does is not serializable via JAX-B.

Is there any way to do this ?

**Comment by elucash** [comment]
Thank you for the interest! You might try to use `@Value.Style(passAnnotations)` style attribute and specify array of special annotation classes which should be copied over from abstract value types to a generated classes.
See [style guide](immutables.github.io/style.html) and [Style.passAnnotations source/doc](https://github.com/immutables/immutables/blob/master/value/src/org/immutables/value/Value.java#L664))
_Note: styles could (and should) be placed on packages or as meta-annotations rather than spilled across individual value types_

**Comment by oroger** [comment]
This is exactly what I needed, thank you !

**Comment by FearlessHyena** [comment]
Sorry to revive an old thread but is there a way to pass all annotations from the abstract class? I have a bunch of annotations and was wondering if there was a more automatic way of passing all of them to the generated class

**Comment by ysndr** [comment]
I believe this was asked for in #475 and is still subject of work

**Comment by elucash** [comment]
@FearlessHyena Usually passing all annotation is not quite safe. If you need this for frameworks, then it's hard to know if they scan supertypes, some of them respect annotation inheritance, some of them will just do something twice for implementation and abstract class if an annotation present on both. In the simplest case, you can try to list all annotation types you want to be copied to implementation class (which you know would be safe to copy) in the style attribute `passAnnotation`. In the more complex cases, one might want to copy attribute level annotations to internal fields or other places and it's not yet implemented in Immutables.

**Comment by FearlessHyena** [comment]
@elucash Thanks for the explanation. It makes sense. I was actually try to generate Modifiable classes so I could use them as Hibernate Entities and possibly in turn create Immutable versions of those . Since I have a lot of annotations including those from the hibernate validator such (NotNull, etc) I was just wondering if there was an easier way to pass those through
As an aside I wonder if you've ever tried something like this for an ORM entity before?
