### ISSUE TITLE
@Value.Enclosing shouldn't imply @Value.Immutable

### ISSUE THREAD

**Issue by rolfw** [immutables/immutables#277]
Note: I'm assuming the statement in the title is true, but feel free to reword if this is by design.

I'm using the `@Value.Include` annotation as suggested by Eugene [in this Google Groups topic](https://groups.google.com/forum/#!topic/immutables/We4G3Krti3g). I use this instead of `@Value.Immutable` on the abstract type, which results in the immutable implementations being generated in a target package of my choice.

I'm also using `@Value.Enclosing` to instruct the compiler to generate the value type `Supplier.ID` as a nested class, i.e. `ImmutableSupplier.ID`. I do this to prevent name conflicts.

The immutable implementations are generated in the target package as expected. However, there are also immutable implementations generated in the package of the type that has the `@Value.Enclosing` annotation. This suggests that `@Value.Enclosing` implies `@Value.Immutable`, which makes sense but it results in duplicate implementations when using @`Value.Includes`.

**Comment by elucash** [comment]
Here I'm not completely understanding your use case, so it will be useful if you provided specific examples. But overall I think that you're doing everything right, and, most probably, what you're seeing is by design. This "enclosing"/"include" functionality is nothing like a totally straightforward or intuitive, but it just works as it is. I'll just try to describe it as I see it works:

There are two aspects here: how you define values and what/how is being generated out of them.
Let's say you define `aa.Customer` and `aa.Customer.ID`
```java
package aa;
public interface Customer {
  public interface ID {}
}
```
Ok, now, when you try to include and generate something out of them in a different package

```java
package bb;
@Value.Include({ aa.Customer.class, aa.Customer.ID.class })
public interface Customers {}
```
So we included `aa.Customer` and `aa.Customer.ID`. What does it mean? The `@Value.Include` annotation actually imply `@Value.Immutable`, but defined externally to the abstract value types.
For the definition above (and assuming default styles are effective), following types will be generated:
```java
bb.ImmutableCustomer
bb.ImmutableID
```
Well, if you add `@Value.Enclosing` to the mix, you'll see implementations will be nested in a class derived from annotated `bb.Customers` top level class, to be specific

```java
package bb;
@Value.Enclosing
@Value.Include({ aa.Customer.class, aa.Customer.ID.class })
public interface Customers {}
// will generate
bb.ImmutableCustomers // just utility enclosing class
bb.ImmutableCustomers.Customer // implementing aa.Customer
bb.ImmutableCustomers.ID // implementing aa.Customer.ID
```
As you see the fact that `aa.Customer.ID` is nested in `aa.Customer.ID` does not impact the way included classes are generated.

On the other hand if you use `@Value.Immutable` and `@Value.Enclosing` directly and in combination and without using `@Value.Include` elsewhere, then you will see somewhat different picture.

```java
package aa;
@Value.Immutable
@Value.Enclosing
public interface Customer {
  @Value.Immutable
  public interface ID {
     @Value.Immutable
     public interface JustForFun {}
  }
}
// will generate
aa.ImmutableCustomer // implementing aa.Customer, which is both enclosing and immutable
aa.ImmutableCustomer.ID // implementing aa.Customer.ID 
aa.ImmutableCustomer.JustForFun // implementing aa.Customer.ID.JustForFun, nesting hierarchy is not preserved
```

As conclusion:

- `@Value.Include` implies `@Value.Immutable`, but not that `@Value.Enclosing` implies immutable
- Generated classes do not preserve nesting hierarchy of abstract value types
- `@Value.Enclosing` provides flat name-spacing, nesting by one level deep in a ad-hoc class which is derived by name from the top level class annotated with `@Value.Enclosing`
- When using both `@Value.Enclosing` and `@Value.Immutable` generated classes maintain an illusion of preserving hierarchy, but in this case generated ad-hoc enclosing class and generated immutable class just happens to be the same for the top-level type annotated with both  `Immutable` and `Enclosing`

In addition you have `@Value.Style(typeImmutable, typeImmutableNested, typeImmutableEnclosing)` style attributes to flexibly define naming patterns of generated classes.

Customization of output package (a yet to be developed feature) can be more useful in this case.
As a practical matter, after using Immutables a lot myself and using nested value types, I now prefer to expose mostly hand-written types and extending generated builders.

```java
@Immutable
interface Customer {
  ID id();
  class Builder extends ImmutableCustomer.Builder {}
  @Immutable
  interface ID {
    @Parameter String value();
    static ID of(String value) {
       return ImmutableID.of(value);
    }
  }
}
// which looks like this ....
Customer c = new Customer.Builder()
      .id(Customer.ID.of("id-122343"))
      .build();
// or using Style.deepImmutablesDetection
Customer c = new Customer.Builder()
      .id("id-122343")
      .build();
```
In the above example I see only an issue with having duplicated `ImmutableID` in the same package if you have many nested `ID`s as in `Customer.ID`, `Order.ID` etc.
As noted in the documentation on the style page, `Value.Enclosing` should be treated as somewhat deprecated or more precisely, a niche solution. I would be reluctant to make `Value.Enclosing` smarter to handle hierarchies, but this should be solved, probably, in some other way.

Currently, I expect that (as discussed elsewhere) we have to add 2 capabilities:
- Output package could be specified or derived using a pattern like "*.immutable" or "*.impl".
- Having style option to generated qualified implementation for nested classes: for `Aaa.Bbb.Ccc` either in the form of `ImmutableAaa_Bbb_Ccc` or `ImmutableAaa.Bbb.Ccc` (and without having to deal with the quirks of  `Value.Enclosing`)

What do you think about the interpretation of the above problems and proposed solutions?
