### ISSUE TITLE
Plural Dictionary as an array in the style can be unweildy

### ISSUE THREAD

**Issue by ldriscoll** [immutables/immutables#283]
We use a single style for all of our projects, so if everyone wants different strange depluralised words, they need to go in the one style.

Is it possible for us to be able to add an annotation at the field level, so that we can give the depluralised name there?  Otherwise, would it be possible to give a resource to load for the depluralizedDictionary, so that we can store all of the mappings in a separate file?

**Comment by elucash** [comment]
Resource loading might be difficult/unreliable to implement due to how compile classpath interacts with compiler/annotation processing classpath. There's option to create a separate annotation which you might stick to some enclosing scope (and unlike styles, merge the content). Per-attribute annotations may also work well, I just hesitate to add another one attribute level-annotation, but it's also might work.
How often some singular/plural form is used only once?
We can even generalize a new annotation to be applicable on any level, from package down to individual attribute. Thank you for the feature request!

**Comment by ldriscoll** [comment]
yeah, I'm not entirely sure how often it would used, but I don't know that we really want all of our plural definitions in our core style.  If we could make it so that a style could be extended, with just a few attributes edited, that would be pretty cool too.

**Comment by elucash** [comment]
The goal to separate stuff is clear here. The ability to extends/partially override styles is a quite general solution that might work well, it's just an area which I tried to avoid for a while ( #189 ). But here we might try to come up with simple extensibility model (which hopefully will not complicate implementation to the death). On the other hand If we want to be able to specify it on per-attribute level, it would be more straightforward to detach depluralize dictionary out of style declaration.
Per attribute solution seems to me like a nice way to specify singlular/plural names, but it might somewhat misguide people to annotate each and every attribute rather than establish ubiquitous dictionaries and try to use them as much as possible, which is maybe not a problem at all, I dunno.

**Comment by elucash** [comment]
2.2-beta released with the new annotation `@Value.Style.Depluralize(dictionary)` . This annotation could be placed on types, packages, as meta-annotations. All applicable dictionaries are merged then.

**Comment by elucash** [comment]
released in 2.2 Thank you!

**Comment by ldriscoll** [comment]
awesome, thanks @elucash
