### ISSUE TITLE
Taking default values from an external value?

### ISSUE THREAD

**Issue by io7m** [immutables/immutables#298]
Hello.

I'm dealing with some code where I have default values that can only be taken from a separate external value that's only available at run-time. Specifically, I'm dealing with material types in a 3D renderer that contain default OpenGL texture values that obviously can't be constructed until an OpenGL context has been created and the textures have been created on it.

One way to handle this is to do:

```
@Value.Immutable
@Value.Modifiable
interface MaterialType
{
  @Value.Parameter
  TextureDefaults getTextureDefaults();

  @Value.Parameter
  @Value.Default
  default Texture2D getAlbedoTexture()
  {
    return getTextureDefaults().getWhiteTexture();
  }

  @Value.Parameter  
  @Value.Default
  default Texture2D getSpecularTexture()
  {
    return getTextureDefaults().getWhiteTexture();
  }
}
```

... and then the material values are constructed by passing in a value of `TextureDefaults`.

The problem: This then means that values of type `MaterialType` all hold references to the `TextureDefaults` type, which has various obscure consequences with regards to sharing resources across OpenGL contexts, and thread safety. Basically, I'd rather not expose access to `TextureDefaults` to any code that happens to receive a `MaterialType` value.

Is there a better way to handle this?

Bear in mind that due to the low-latency, low-garbage nature of the code, I do actually use the mutable variants of the generated types and would therefore prefer solutions that don't make it unpleasant to do that.

**Comment by elucash** [comment]
I had similar needs one day and ended up with almost the same solution. It might be useful is to use abstract base class instead of interface and make `getTextureDefaults` protected. I guess, overall, this is more like general problem with dependency injection and immutable composition.

As a sidenote, you can use `Style(allParameters= true)` to automatically turn all attributes into parameters if needed. If you use interfaces with a lot of default methods for `Value.Default` attributes, then you can also use `defaultAsDefault = true` style attribute to make default attributes out of no-arg default methods automatically.

**Comment by io7m** [comment]
Ok, thanks!

Looks like I'll be sticking with this method.
