### ISSUE TITLE
non-final generated classes

### ISSUE THREAD

**Issue by qinfchen** [immutables/immutables#318]
Is there a support for non-final generated classes?

**Comment by elucash** [comment]
`@Value.Modifiable` generated modifiable types can be non-final if using `Style(create="new")`. But I would say it make sense since there's no reason for immutable types to be non-final. If you need just "some" implementation than mutable instances might fit the bill. Methods can be added to immutable type by extending/implementing supertype rather than by extending immutable type.

**Comment by qinfchen** [comment]
We are making the abstract class package private and the generated class public as it enables less boilerplate code on builders and serialization/deserialization. But we can't no longer create mocks. For unit tests, using builder to build the value classes is fine and i was curious if there is way to ease process.

**Comment by elucash** [comment]
I don't want to sound as silly scholar (probably will): "you don't to need mock value object, because they are values". And if you really really need that, there's heavy artillery like Powermock.

**Comment by qinfchen** [comment]
Completely agree. Value classes don't need to be mocked
