### ISSUE TITLE
@Gson.TypeAdapters with @Value.Immutable(builder = false)

### ISSUE THREAD

**Issue by fAns1k** [immutables/immutables#357]
```java
@Value.Immutable(builder = false)
@Gson.TypeAdapters
public interface ImmutableObject {
    @SerializedName("parameter")
    @Value.Parameter
    String parameter();
}
```

Gson generator could not generate proper result class with regard to @SerializedName, so as a result in generated code i have:

```java
    @Override
    public void write(JsonWriter out, ImmutableObject value) throws IOException {
      if (value == null) {
        out.nullValue();
      } else {
        writeImmutableObject(out, value);
      }
    }

    private void writeImmutableObject(JsonWriter out, ImmutableObject instance)
        throws IOException {
      out.value(instance.parameter());
    }
```
with no reference to original name of my parameter

**Comment by elucash** [comment]
Thank you for reporting this. This is expected behavior. If you disable builder, you force object to use serialization to tuple of constructor arguments, so `@SerializedName` annotation have no effect in this case. You can read more about it in the documentation http://immutables.github.io/json.html#tuples-of-constructor-arguments
 Once you switch builder on, you'll have it applied. Remember that you can have constructor and builder at the same time so this should not be a problem. In the example you provided the name in the annotation is the same as the attribute name, so you'll have to change serialized name to see any effect at all.

**Comment by fAns1k** [comment]
Thanks for explanation, i lost this part.
