### ISSUE TITLE
Builder methods for fields of base class.

### ISSUE THREAD

**Issue by zstd** [immutables/immutables#371]
Hello.

I have such immutable object. It represents Siren4J resource:
```
@Value.Immutable 
 @Value.Style(
        init = "with*",
        typeAbstract = {"Abstract*"},
        typeImmutable = "*",
        passAnnotations = {Siren4JSubEntity.class, Siren4JEntity.class}
 )
 @Siren4JEntity(suppressClassProperty = true, entityClass = "AssessmentInfo")
 public abstract class AbstractAssessmentInformationResource extends BaseResource {
    
    @Siren4JSubEntity(rel = "assessment-data")
    public abstract Collection<AssessmentDataResource> getAssessmentDataResources();
    public abstract String getCode();
    public abstract String getDescription();
}
```
My class is extending third-party class BaseResource.
Inside the builder I see only methods for my class and not for BaseResource.

Is there a way to make generated builder also have methods from BaseResource.

**Comment by elucash** [comment]
Generated class/builder implements all inherited abstract or "default" attributes, if BaseResource define such attributes, `AssessmentInformationResource.Builder` will have initializer for it implemented.

```java
interface A { int a(); }
@Immutable interface B extends A { int b(); }

B b = ImmutableB.builder()
    .a(1) // <-- inherited from A
    .b(2) // <-- defined in B
    .builder();
```

**Comment by zstd** [comment]
But what if the class that is extended is not abstract:

```
class A { protected int a; }
@Immutable abstract class B extends A { abstract int b(); }

B b = ImmutableB.builder()
    .a(1) // <-- inherited from A ????
    .b(2) // <-- defined in B
    .builder();

```

**Comment by elucash** [comment]
It's ok for class to not be abstract, but only abstract or special non-abstract (like `@Value.Default`) methods will be implemented. Fields doesn't count. In your case the field is mutable, but Immutables processor will not generate attributes baked by unsafe (for immutability) fields. Having final fields force coding a constructor and this doesn't fit with Immutables as well. Just change the objects to use abstract methods attributes if you can. Otherwise just consider writing subclass manually as there are too many deviation from consistent immutable object we can generate. I know Lombok does messing with changing fields to final behind the scenes by AST manipulations, but it's just make it non-JLS compliant dialect of Java

**Comment by zstd** [comment]
Thanks, @elucash for detailed explanation.
Can you please point me to section in docs that describes that, because I've not found that from docs and suppose it is a little tricky question for new users of your great library?

**Comment by elucash** [comment]
it's totally overdue, sorry, but to finish this thread, these things are covered in the guide
http://immutables.github.io/immutable.html#concepts
http://immutables.github.io/immutable.html#builder
