### ISSUE TITLE
Gson "auto boxing/unboxing" ?

### ISSUE THREAD

**Issue by ncornette** [immutables/immutables#407]
Hi, and thank you for this awesome lib!

This is an issue I often face with: let's say I have an object with a single attribute

```json
{
  "message":"Hello"
}
```

```java
@Gson.TypeAdapters
interface Greeting {
    String message();
}
```
But I have this json instead, where the value is nested, and I would like to skip the object and get the value directly for both serialization and deserialization with the same interface : 
```json
{
  "message":{"string":"Hello"}
}
```

A imagined a `@Gson.Indirect` or similar annotation could do the trick. 
```java
@Gson.TypeAdapters
interface Greeting {
    @Gson.Indirect("string")
    String message();
}
```

Is this realistic or is there already a way to do this?

**Comment by elucash** [comment]
Hi, thank you for raising this! There's the feature of constructor argument serialization
http://immutables.github.io/json.html#tuples-of-constructor-arguments

in nutshel, declare single constructor parameter and disable builder, then during serialization object will act as invisible wrapper for containing value.

```java
@Gson.TypeAdapters
@Value.Immutable(builder = false)
interface Message {
    @Value.Parameter
    String value();
}

@Gson.TypeAdapters
@Value.Immutable
interface Greeting {
    Message message();
}

Greeting greeting = ImmutableGreeting.builder()
    .message(ImmutableMessage.of("Hello!"))
    .builder()
```

```javascript
{
    "message":  "Hello!"
}
```

**Comment by ncornette** [comment]
Thank you Eugene, but what I wanted was the exact opposite :-) 

The idea was to construct and read messages like simple strings. 

I have this json: 

```
{
  "message":{"string":"Hello"}
}
```

And I want to expose through this simplified interface, this is where the string needs to be unwrapped from the json object : 
```java
interface Greeting {
    String message();
}
```

The constructor argument serialization feature on the other hand can give me all the flexibility I need for serialization, is more open to extension and without touching the interface afterwards. So I will change my interface...

But there are still use cases where values are nested into a single value json object for no reason, and where I would like to extract the value directly, and I don't see how it can be done...

**Comment by elucash** [comment]
Usually, the kind of things you want to do can be achieved in Gson by plugging custom type adapters, especially when applying it in a targeted manner to specific fields, etc. It's even more complicated by the fact that Immutables' Gson generated type adapters directly serialize strings and primitive types without looking up for type adapters that could.

We had an experimental (currently decommissioned until we would able to productionalize it if ever) Moshi generator and there was a way to look up custom adapter by applying qualifying annotation (akin to Guice).

I don't know how constrained you are with regard to using only simple types (primitives, strings), but if creating wrappers is not an issue, I would create such wrapper types with custom type adapters if generated adapters would not be flexible enough.

```java
interface Greeting {
   StringValue message();
}
// or even using generics (but some gymnastics required
// implementing custom type adapter factory)
interface Greeting {
   Val<String> message();
}
```

Yet another possibility is to create special type adapters that may wrap JsonReader / JsonWriter so that structure could be augmented on the fly with some buffering overhead.

I may not remember correctly, but `@Nullable` fields have forced type adapter acquisition even for Strings and primitive-wrapper types. This may be used a loophole for injecting custom adapters also.
