### ISSUE TITLE
headerComments works only sometimes

### ISSUE THREAD

**Issue by cal101** [immutables/immutables#413]
Hi!

To get aware of changes in the generated files by generator or annotation changes I check the generated files into our version system. 
So I noticed that the effect of "headerComments" is sometimes false, sometimes true.
Even If I set it explicitly to true in style annotation.
Here the result I sometimes get after setting it to true:

   /**
-   *@see PropertyDefinition#UIP_FACET 
+   * @return The value of the {@code isFacetEnabled} attribute
    */
   @Override
   public boolean isFacetEnabled() {

You see that my comment was replaced with standard comment.

Otherwise it's working great.

Cal

P.S. 
Regarding our discussion about converting a deep structure with/without some context:
For Deep structures I use a thread local based approach to get the same immutable instance for the same mutable instance when converting my graph of mutable objects to immutable. Works good enough for entities so far.
One piece is missing and I had to hack it:
We have a tree of topics and one of them is the default topic which is just an extra reference to the Topic on TopicTree level:

TopicTree:
   Map<String,Topic> getTopics()
   Topic getDefaultTopic()

I could not find a way to make return getDefaultTopic return one of the converted Topic instances from the Map without smelly hacking.

**Comment by elucash** [comment]
Hi there!
Header comments feature needs to get a source code. Under certain circumstances such as incremental compilation or some other (hard to predict) compilation modes, a source code might be unavailable. Currently, I would suggest that having header comments is probably a best effort functionality as there's no standard API to get it (and given that how standard API has flaws and bugs in both Javac and Eclipse we could not desire any better). Please, if you help find/spot any specific issue, we can fix it, otherwise I feel it as an utter nightmare to dig into why compiler is not behaving as we are assuming ). 

As about TopicTree, I need to get my head around it, maybe there will be some ideas )

**Comment by cal101** [comment]
OK, no need to open that can of worms for me.
So you expect that when setting headerComments to false the behavior should be predictable?
I assumed "false" to be default.

**Comment by elucash** [comment]
I'll reread tomorrow morning and will get better understanding of the issue )

**Comment by cal101** [comment]
Setting to false explicitly seems to disable the feature as expected.

**Comment by elucash** [comment]
I've reviewed the code for this and I was unable to see any place that can possibly produce erratic behavior. My only thought about how such instability might occur is that it might be related to incremental compilation. Can you, please, create some mininal repro which can experience instability in a course of several builds?

**Comment by ldriscoll** [comment]
it's worth noting that the incremental build issues is now fixed in maven compiler 3.5.1 https://issues.apache.org/jira/browse/MCOMPILER-236

**Comment by elucash** [comment]
just wanted to clarify what I was thinking about: stuff like `getDocComment` in the standard API, or using non-standard APIs might fail to return anything if annotation processor invoked against models which are build from already compiled class files as opposed to source files. It might happen when you analyze classes that came from third-party jar file, or from other module (like maven module). But here we have sometimes sources present, sometimes not, so other jar/module is not the case, apparently. Here's the example with incremental compilation. Let's say we have 2 interfaces in the same maven module (or whatever build system).

```java
//abc/Y.java
package abc;
interface Y {
  /** super cool field. */
  int my();
}
//abc/Z.java
package abc;
@Value.Immutable
interface Z extends Y {
   /** not so cool field.*/
   String other();
}
```
Let's say you compile them and have something akin generated

```java
//abc/ImmutableZ.java
final class ImmutableZ {
  ...
  /**
   * super cool field.
   */
  int my() {...

  /**
   * not so cool field.
   */
  String other() {...
}
```

Let's say, you change Z to put a lot cooler javadoc

```java
//abc/Z.java
package abc;
@Value.Immutable
interface Z extends Y {
   /** totally awesome field! */
   String other();
}
```

And here incremental compilation will (if enabled) kick in and compile only a single Z.java class, while having Y supplied via classpath, from Y.class (rather than Y.java). The generated code then might look like this

```java
//abc/ImmutableZ.java
final class ImmutableZ {
  ...
  /**
   * @return The value of the {@code my} attribute
   */
  int my() {...

  /**
   * totally awesome field!
   */
  String other() {...
}
```

Voilà
For the reference, here's part of template code, from where it could be seen how this can happen where docComment is not available:

```
/**
  [if v.docComment]
[for d in v.docComment]
 *[d][-- no space before doc line!]
[/for]
  [else]
[if v.arrayType]
 * @return A cloned {@code [v.name]} array
[else if v.generateDerived]
 * @return The computed-at-construction value of the {@code [v.name]} attribute
[else]
 * @return The value of the {@code [v.name]} attribute
[/if]
  [/if]
 */
```

**Comment by cal101** [comment]
Our case seems to be indeed an incremental oracle compiler issue.
What I don't understand is that setting headerComments=false seem to make a difference.
Cosmic radiance I guess. ;-) 
Good enough for me.
More important issues than this.
