### ISSUE TITLE
[Question] Anyway to make generated code compatible with jdk 1.6?

### ISSUE THREAD

**Issue by nuclearg** [immutables/immutables#415]
I'm writing a lib, heavily using Immutables. It works very well.

But one user of my lib reports my lib broken in JDK1.6. I found `java.lang.Objects` using by generated code is added since jdk1.7, which is not supported in jdk1.6.

After google, I found there seems someway to make Immutables compatible with 1.6, such as [this issue](https://github.com/immutables/immutables/issues/378), but I don't know how.

Thanks!

**Comment by elucash** [comment]
Hi! There's 2 options I can think of right now. First is to add Guava to the compilation classpath, so it will use Guava utilities instead of `java.lang.Objects` etc. The other one option you may try is to add `org.immutables:android-stub` artifact during compilation, it will force generation of utilities without using either `java.lang.Objects` or Guava. Let us know if any of those can work for you.

**Comment by nuclearg** [comment]
I added `org.immutables:android-stub`, it works like magic! Thanks!

**Comment by elucash** [comment]
Great! Just a note, you need this dependency only for compilation, do not redistribute it as runtime (well it's useless anyway). 'provided' or 'compileOnly' scope would be the best.
