### ISSUE TITLE
FieldNamingPolicy for Gson throws NoClassDefFoundError(ReflectionFactory)

### ISSUE THREAD

**Issue by TillSimon** [immutables/immutables#447]
I manage to integrate Immutables with Retrofit with a Gson-TypeAdapterFactory created with the `@Gson.TypeAdapters` annotation. Now what I can't get to work is a FieldNamingPolicy.

Steps I did:
1) Make gson dependency runtime-available (right?) by exchanging `provided ` with `compile`:
`apt 'org.immutables:value:2.3'
provided 'org.immutables:value:2.3'
compile 'org.immutables:gson:2.3'`

2) In the **package-info.java** add `@Gson.TypeAdapters(fieldNamingStrategy = true)`

3) Configure my Gson object
`gson = new GsonBuilder().setFieldNamingPolicy(FieldNamingPolicy.LOWER_CASE_WITH_UNDERSCORES)`

When the first effected model class needs to be parsed at runtime, it throws this:

`NoClassDefFoundError: Failed resolution of: Lsun/reflect/ReflectionFactory;
at org.immutables.gson.adapter.FieldNamingTranslator.<clinit>(FieldNamingTranslator.java:48)`

Any hints?

**Comment by elucash** [comment]
Field naming strategy is only working on oracle/sun JRE and in the absence of any restrictions such as imposed by security managers. As such it will not work on Android or other environments as GSON only supports this for reflective (default) type adapter.
Field naming strategy is not accessible to custom type adapters such as generated ones, also it works on fields rather than attribute methods, therefore it heavily uses reflection hacks.
Dependency on the Oracle JVM is declared here: http://immutables.github.io/json.html#field-naming-strategy.

From what I read, on Android, and in general, folks are usually recommending against using strategy in favor of naming fields directly or annotate with `SerializedName` annotation: https://publicobject.com/2016/01/20/strict-naming-conventions-are-a-liability/

**Comment by TillSimon** [comment]
Thank's heaps for your prompt and accurate answer. I read the part about Oracle JVM, but didn't quite connect the dots. Maybe an explicit mentioning of Android might help for people like me :)

**Comment by elucash** [comment]
I'll add a note about Android, good suggestion!

**Comment by elucash** [comment]
added a quick note the documentation
