### ISSUE TITLE
isInitialized get serialized to JSON

### ISSUE THREAD

**Issue by brentryan** [immutables/immutables#474]
We've discovered an undersirable property showing up in our json because of this:

```
  /**
   * Returns {@code true} if all required attributes are set, indicating that the object is initialized.
   * @return {@code true} if set
   */
  public final boolean isInitialized() {
    return true;
  }
```

Can we update immuables when used with jackson to have this?

```
  /**
   * Returns {@code true} if all required attributes are set, indicating that the object is initialized.
   * @return {@code true} if set
   */
 @JsonIgnore
  public final boolean isInitialized() {
    return true;
  }
```

**Comment by elucash** [comment]
Thank you for reporting this! Right now I'm quite confused because we're not generating `isInitialized()` method in immutable objects. Can you clarify what kind of object is used, is it Modifiable object or builder is getting serialized? It may be that I just forgot some pieces of functionality we have, but an expanded example will definitely help. In any case, adding `@JsonIgnore` should not be a problem

**Comment by brentryan** [comment]
This is being generated on modifiable objects.  So it's only a problem for @Modifiable generation.

**Comment by elucash** [comment]
released in 2.3.9

**Comment by brentryan** [comment]
@elucash Did you mean for this fix to only work if you apply this style?

Style.forceJacksonIgnoreFields = true

**Comment by elucash** [comment]
Apparently, yes,` forceJacksonIgnoreFields = true` shoud do the trick. As a reminder, modifiable object was never actually designed to be properly serializable to JSON, so caveat emptor
