### ISSUE TITLE
Extend `@NaturalOrder` support to other collection types

### ISSUE THREAD

**Issue by Stephan202** [immutables/immutables#516]
The `@NaturalOrder` annotation currently applies to `SortedSet`s, `SortedMap`s, and (a number of?) their subtypes. If the annotation is applied to a `List`, say, then it has no effect.

I'd like to propose that support is also added for other types, in cases where this makes sense. Examples:
* `List`.
* `Map` (through use of `LinkedHashMap`).
* Guava's `Immutable{Set,List}Multimap` (the builders accept comparators).

I imagine this may not be trivial to add. Before I attempt to dive in: do you agree with this proposal in principle?

**Comment by elucash** [comment]
@Stephan202 Thank you for the proposal. I don't think this functionality is necessary, mostly because it makes things needlessly complicated from the standpoint of semantics. If you declare list - it imposes insertion ordering. When you have Map, well, a map does not guarantee any ordering, but an immutable implementation will also follow insertion ordering (unmodifiable `LinkedHashMap` or `ImmutableMap`). Use `Sorted/NavigableSet/Map` to keep the content auto-sorted, because of the nature of the sorted collections, not because there's an annotation. `@NaturalOrder` and `@ReverseOrder` are simply to make it explicit what comparator will be used. If you need a custom comparator, you're also "out of luck": just create `SortedSet` fully outside the builder.
I know there's always a tension to sweep as much as possible under the rug of the code generation and have no boilerplate with only handful of fancy annotations on top (sorry, I'm guilty in this too). But here is exactly the case where explicit code would work best. You either create and sort list before setting onto builder, or you can use sorted views using `@Value.Derived` attribute. There's a recent post on StackOverflow with the similar example: http://stackoverflow.com/questions/41376633/how-would-it-be-advised-to-get-immutables-to-build-this-object-with-this-sort/41378182#41378182

**Comment by elucash** [comment]
Although it would be really great if someone helped to get `SortedMultiset` and `SortedMultimap` supported via  `@NaturalOrder` and `@ReverseOrder` in the same manner as `SortedSet` and `SortedMap` are supported. The entry point in the source code would be `AttributeTypeKind` enum, and then some accessor and a number or template changes required for this to work.

**Comment by Stephan202** [comment]
Thanks for the quick response. Indeed, as you mention in the SO answer, my current workaround involves `@Value.Check`. (And I learned about the need to check for "already sorted" the hard way, i.e. through a `StackOverflowError` ;).) I'll play a bit with `@Value.Derived` to see whether I'd like that better.

I'll try to set aside some time to add support for `SortedMultiset` and `SortedMultimap`.

About not supporting `@NaturalOrder` in other scenarios: though I had hoped for another answer ;), would you then agree that the annotation processor should emit a warning/error if `@NaturalOrder` is applied to unsupported types?

**Comment by Stephan202** [comment]
NB: Guava does not provide a `SortedMultimap`. (My original motivation for filing this ticket was the desire to store a normalized (= sorted, in my case) `ImmutableSetMultimap`s...)

So I'll just look into adding support for `SortedMultiset`s.

**Comment by elucash** [comment]
Funny, I thought it was strange I couldn't find `SortedMultimap` ;)

**Comment by elucash** [comment]
released in 2.4.0, thank you!
