### ISSUE TITLE
Add multiple ways to set attributes

### ISSUE THREAD

**Issue by Diagoras** [immutables/immutables#522]
Is there a way to define multiple ways to set an attribute, similar to how an `Optional<T>` attribute can be set both by passing an `Optional<T>` to the builder or by passing a `T`?

I'm looking to provide clients of my library with the ability to either pass a `TypeReference<T>`, or a `Class<T>` which a `TypeReference<T>` can then be derived from. While default/derived attributes are some help, neither gives you a way to create a builder that allows an attribute to be set once and only once in two different ways.

**Comment by elucash** [comment]
Hi @Diagoras, a "nice" solution would to use special extensions called _encodings_. In this way, you can customize how accessors/initializers are implemented for some type (`TypeReference` in your case) and add supplementary ones.
To get started, please, read the following info:
feature issue #363
incomplete guide/tutorial http://immutables.github.io/encoding.html
example project with Javaslang collection encodings https://github.com/immutables/immutables-javaslang

**Comment by Diagoras** [comment]
Thanks @elucash, I'll do that.

**Comment by io7m** [comment]
@Diagoras: Small note: It's common to handle this sort of thing with something analogous to the `Either` type used in various languages. [Javaslang](http://www.javaslang.io/javaslang-docs/#_either) has a Java implementation, for example. The thing is: If you're providing something that's either a `TypeReference` or a `Class`, then presumably users are going to have to deal with using something that's `TypeReference` or a `Class` and therefore it's good to have that notion of choice present in the types so that it's clear users have to pick one or the other.

```
@Value.Immutable
interface ExampleType<T>
{
  @Value.Parameter
  Either<Class<T>, TypeReference<T>> typeReference();
}
```

etc.

I'm actually looking to add support to the Javaslang encodings to provide builder methods that let you set either possible choice directly, when an attribute is of type `Either<A,B>`.

**Comment by Diagoras** [comment]
@io7m I thought of that as well, though I'm trying to avoid adding too many dependencies to my library. That builder would be very nice, though. Like a staged builder with two possible choices that lead to the next stage?

**Comment by io7m** [comment]
Yeah, I only mention Javaslang as it has an Either type already. It's fairly easy to leverage `immutables` to define your own sum types:

```
  interface ReferenceType<T>
  {
    <R> R match(
      Function<ReferenceRefType<T>, R> on_reference, 
      Function<ReferenceClassType<T>, R> on_class);
  }

  @Value.Immutable
  interface ReferenceRefType<T> extends ReferenceType<T>
  {
    @Override
    default <R> R match(
      Function<ReferenceRefType<T>, R> on_reference,
      Function<ReferenceClassType<T>, R> on_class)
    {
      return on_reference.apply(this);
    }
    
    @Value.Parameter
    TypeReference<T> value();
  }

  @Value.Immutable
  interface ReferenceClassType<T> extends ReferenceType<T>
  {
    @Override
    default <R> R match(
      Function<ReferenceRefType<T>, R> on_reference,
      Function<ReferenceClassType<T>, R> on_class)
    {
      return on_class.apply(this);
    }

    @Value.Parameter
    Class<T> value();
  }
```

You could then have:

```
@Value.Immutable
interface ExampleType
{
  @Value.Parameter
  ReferenceType<T> reference();
}
```

Which would yield a generated API that looks like:

```
Example e = Example.of(ReferenceClass.of(Integer.class));

e.reference().match(
  er -> { ... Do something with ReferenceRefType here ... },
  ec -> { ... Do something with ReferenceClassTyoe here ... });
```

This has the usual benefits such as getting the compiler to tell you all of the places in code that need to be changed when a new case is added (because any calls to the `match` method will become compilation errors).

**Comment by io7m** [comment]
I'm not sure about the staged builders yet as I haven't actually used them before.

**Comment by elucash** [comment]
I doubt that staged builder will work "properly" with encoded types, it will leave all collection, optional and encoded attributes on the last stage. As I see it this is less about exlusive choice, but more about convenience, providing shortcuts, as in the end you want unified type reference, not a choice of class or type reference, also there could be more than 2 construction paths for the attribute value.
