### ISSUE TITLE
generates incorrect Builder method when have Builder as an interface

### ISSUE THREAD

**Issue by w268wang** [immutables/immutables#532]
I have a class looks like this
```
@Value.Immutable
public abstract class A {
    public abstract ImmutableSet<Member> memberSet();
    public static Builder builder() {
        return AImpl.builder();
    }
    public interface Builder {
        Builder setMemberSet(ImmutableSet<Member> elements);
        A build();
    }
}
```
But the generated builder have the following 4 methods
```
Builder addMemberSet(Member element);
Builder addMemberSet(Member... elements);
Builder setMemberSet(Iterable<Member> elements);
Builder addAllMemberSet(Iterable<Member> elements);
```
instead of the desired
```
Builder setMemberSet(ImmutableSet<Member> elements)
```
and the mismatch cause a compilation error. Is there any way to fix this?
PS: I choose to have the interface of the Builder inside this class is just to improve the readability of the code, so that people don't need to go to the implement class to see the interface of the methods.

**Comment by elucash** [comment]
I'm sorry, but Immutables behaves differently from other toolkits (autovalue?), when we recognize special types (such as `List`, `Set`,  `Map`, `Immutable*` variants) we generate convenience methods to set them on a builder. And, what might seems strange, this is exactly the value Immutables have for people. Since you're hiding builder methods behind `Builder` interface, you can you switch to more permissive signature and you're done: 
```java
public interface Builder {
   Builder setMemberSet(ImmutableSet<Member> elements);
}
```

In order to fully customize generation of the types you want there's a more heavyweight solution available, please see the following instructions: https://github.com/immutables/immutables/issues/521#issuecomment-271666775

**Comment by w268wang** [comment]
That makes sense, thanks!
