### ISSUE TITLE
Accessing builder fields when extending from the generated one

### ISSUE THREAD

**Issue by before** [immutables/immutables#535]
I need access to the fields of the builder to avoid building the entire object. Could we make the fields package private when extending the generated builder?
```Java
@Value.Immutable
abstract class ValueObject {

    abstract ImmutableList<Field> fields();

    static class Builder extends ImmutableValueObject.Builder {

        Builder addField(String name) {
            int position = build().fields().size(); // currently used option
            //int position = _fields.build().size(); // preferred option
            addFields(Field.of(name, position));
            return this;
        }

    }

}
```

**Comment by elucash** [comment]
Hi @before thank you for the suggestion! At this time, there's not a lot of resources to implement issues like this one. However, we would accept PR, which does the following:

* Provides `org.immutables.builder.Builder.AccessibleFields` annotation on the builder or introduces `builderAccessibleFields` style switch.
* Generates `protected` modifiers on all builder fields (except special tracking fields) instead of `private` if this feature is enabled.

**Comment by before** [comment]
Hi @elucash, I filed the PR #538 today. Would appreciate feedback on this.

**Comment by elucash** [comment]
@before Thank you, very good start! I do see couple of things, will comment on PR lines

**Comment by before** [comment]
@elucash I made some changes regarding to your comments. Thank you for your feedback.

**Comment by elucash** [comment]
Excellent! Merged! Thank you!
