### ISSUE TITLE
Style annotations must End with "Enabled" to propagate @Encodings.

### ISSUE THREAD

**Issue by nikron** [immutables/immutables#537]
We want to propagate an internal option encoding on a "default" style, (so we don't have to add the Enabled annotation to all usages of that option class).

However, it looks like immutables currently doesn't look for encodings  unless that annotation ends with "Enabled".  I don't know if this was intentional, and doesn't appear to be documented.

Looks like a somewhat simple fix, if not intentional (which I'd be happy to submit a PR for).

**Comment by elucash** [comment]
Thank you for reporting this. Yes, we're avoiding introspect meta-annotations which don't have `*Enabled` suffix. But since encoding compiler is generating annotations with `*Enabled` suffix anyway, this should not be a problem. If you want to hack around, just name your annotation with `Enabled` in the end. I don't have precise data, but somewhat hesitate always inspect all annotations of annotations as this may slow down the compilation phase. If you can prove that the compile-time overhead is negligible on the no-nonsense and sizable codebase, I would be glad to remove this "limitation".

**Comment by nikron** [comment]
I think you are saying it's too expensive to check all annotations and see if they are in fact meta annotations with encoding metadata.  I'm proposing that that annotations found by `CustomImmutableAnnotations` are always checked to see if they are meta annotations with encoding meta data.  You could even only check annotations of on the custom annotation with the suffix "Enabled".

**Comment by nikron** [comment]
Thanks for responding by the way, I think the library is awesome and appreciate your work.

**Comment by elucash** [comment]
@nikron you're right, it actually performs not as I've imagined it should. While revising the code, it was changed to see if

* Annotation name ends with `"Enabled"`
* or is annotated with style annotation
* or is one of the custom immutable annotation

The fix will be in the next release, in a meanwhile, you can use snapshots or build from the source.

**Comment by elucash** [comment]
Fix released in 2.4.3. Thank you!
