### ISSUE TITLE
New Optional object created on each getter call

### ISSUE THREAD

**Issue by ufoscout** [immutables/immutables#556]
When an Optional field is declared in an Immutable interface, the generated getter creates a new Optional object on each call:

```java
   private final String value;
   ...
  /**
   * @return The value of the {@code value} attribute
   */
  @Override
  public Optional<String> getValue() {
    return Optional.ofNullable(value);
  }
```
Since the Optional itself is an immutable object, this implementation is not optimal. It would be more natural to declare the "value" attribute directly of type Optional and always return it:
```java
   private final Optional<String> value;
   ...
  /**
   * @return The value of the {@code value} attribute
   */
  @Override
  public Optional<String> getValue() {
    return value;
  }
```

**Comment by elucash** [comment]
The current implementation is intentional, mostly because of the way how `java.util.Optional` is supposed to be used according to Java 8 folklore (see #240). However, you can override how type is implemented using the encoding functionality, please, see directions here https://github.com/immutables/immutables/issues/521#issuecomment-271666775. As another workaround, you can also use Guava's `Optional` or Fugue's `Option` which are being embedded without "unboxing" .
