### ISSUE TITLE
Generating non-public FooBuilder class rather than public ImmutableFoo

### ISSUE THREAD

**Issue by mcintyret** [immutables/immutables#568]
Hi

Something very strange is happening with my build. For the simple definition

```
@Immutable
public interface Foo {
}
```

I used to get

```
public class ImmutableFoo implements Foo {
}
```

But am now getting

```
final class FooBuilder {
   private static class ImmutableFoo {
   }
}
```

I have no idea how this has changed! 

It is particularly problematic since the generated class has package-private scope so it's impossible to create a Foo outside of the package.

I am using Immutables 2.4.3, and IntelliJ's built-in annotation processor.

**Comment by elucash** [comment]
Have you added some module which can impose special style on a package (parent package)? Also, styles are agressively cached, if you experimented with styles it's worth to restart IDE

**Comment by mcintyret** [comment]
Hmm by not declaring a dependancy on a certain library it reverts to normal behaviour.

Thing is, I need that library.

Is there any way I can prevent other jars on the classpath overriding the default style?

**Comment by elucash** [comment]
There are 2 things you should do
1. Report to library creators that they may be leaking styles on a too wide scope (like annotating `com` package instead of `com.acme.library` one. The latter should be more appropriate).
2. You can override this on the level of your package or type just by putting `@Value.Style` with no additional settings

**Comment by mcintyret** [comment]
That's fixed it! Thanks Eugene

**Comment by elucash** [comment]
thank you, closing
