### ISSUE TITLE
Support for groups in validation

### ISSUE THREAD

**Issue by priyadarsh** [immutables/immutables#572]
I am able to leverage hibernate validation framework with Immutable as below. But I am not able to set my custom Groups like the below where the validation is skipped because there is not option of setting Groups while validating.

----  no option of setting the groups in the generated Immutable class
   Set<ConstraintViolation<ImmutablePlace>> constraintViolations = validator.validate(instance);

--- NotNull validation with custom group T.class
@Value.Immutable
@Value.Style(validationMethod = Value.Style.ValidationMethod.VALIDATION_API, passAnnotations = NotNull.class)
public interface Test {
  @NotNull(groups = T.class)
  String getOn();
}

**Comment by elucash** [comment]
Hi @priyadarsh The default integration path you've is intentionally designed to be dead-simple validation during construction but lacking configuration. The reason is that there are endless ways to configure when and how to validate and what validator instance to use etc.

On one hand, you can try to use Default validation group. However, a more flexible way is DIY integration using special validation mixin. Please read about how to use it here: https://github.com/immutables/immutables/issues/26#issuecomment-242283196
Using this approach you're in control when to validate and which validation group to use.

Hint: If using custom mixin validation and you want to rely on `@NotNull`, skipping built-in null validation in Immutables, use `validationMethod = Value.Style.ValidationMethod.NONE`

Let us know if it helps
