### ISSUE TITLE
Builder generated is failing with generics with extends

### ISSUE THREAD

**Issue by jfreire** [immutables/immutables#587]
Here is an example :

@Value.Immutable
public interface Test {

	<T extends Enum<T>> T prop();
}

that generate

public final class ImmutableTest implements Test {
  private final T<TextendsEnum<T>> prop;
...

**Comment by elucash** [comment]
Hu @jfreire  thank you for reporting this. I'll see if we can handle this any better, but in general Immutables processor doesn't support generics in attribute types, only on value object type. This is because it's hard to make sense how to implement it. Also, latest version has unfortunate regression in handling recursive generics in abstract value types (#580), but we expect to fix it promptly.
