### ISSUE TITLE
Why do generated objects implement `hashCode` instead of using `Objects#hash`?

### ISSUE THREAD

**Issue by zmanji** [immutables/immutables#629]
I noticed that the generated `hashCode` looks like:
```
  @Override
  public int hashCode() {
    return hashCode;
  }

  private int computeHashCode() {
    int h = 5381;
    h += (h << 5) + name.hashCode();
    h += (h << 5) + age;
    h += (h << 5) + strings.hashCode();
    return h;
  }
```

Why do this if  [Objects#hash](https://docs.oracle.com/javase/8/docs/api/java/util/Objects.html#hash-java.lang.Object...-) is available?

**Comment by elucash** [comment]
In general, people want `hasCode` to be as optimized as possible and having a good bit distribution. `Objects.hash` creates an array for each invocation and also boxes each argument to an `Object`. In your case (from the snippet above) the hashCode is precomputed in constructor, but even if not, people asked it to be as low overhead as possible. Using annotation processor we can generate optimal code as it would be daunting to write such code manually. When Guava is on the classpath, a generated `toString` method  is using `MoreObjects. toStringHelper` for nice-looking code. This is because `toString` is not considered performance sensitive, but `hashCode` or `equals` are performance critical.

**Comment by zmanji** [comment]
Thanks for the explanation. It might be worth while to mention this in the documentation.
