### ISSUE TITLE
@CheckForNull annotation is mixed with @Nullable.

### ISSUE THREAD

**Issue by vbychkovskyi** [immutables/immutables#656]
Hi, we're using Immutables version 2.5.6 which has support for `@CheckForNull` nullable annotation.
I encountered that `CheckForNull` is mixed with `javax.annotation.Nullable` in my classes.

See my code example.
```
    @Value.Immutable
    @Value.Modifiable
    @JsonIgnoreProperties("initialized")
    @JsonDeserialize(builder = ImmutableRequestOption.Builder.class)
    public interface ValueClass {

        String getName();

        @CheckForNull
        String getValue();
    }
```
In generated immutable value class

```
    private final **@Nullable** String value;
```

```
    private ImmutableValueClass(String name, @Nullable String value) {
        this.name = name;
        this.value = value;
    }
```
```
    public final ImmutableValueClass withValue(@Nullable String value) {
      if (Objects.equals(this.value, value)) return this;
      return new ImmutableValueClass(this.name, value);
    }
```
That's not what I'm expecting. I'm expecting `@CheckForNull` to be instead of `Nullable` in this case.
We're using Find Bugs and AFAIK it supports only `@ChechForNull`

I tried to implement `CheckForNull` support couple of weeks ago.
I've chosen the approach which allows to configure custom nullable annotation in `Value.Style`

@elucash please, take a look at my pull request #655.
I'd appreciate your feedback on this issue and PR #655.

**Comment by elucash** [comment]
In light of recent addition of `nullableAnnotationName` this may be solved for you, but I would say that originally it is was by design that accessor annotation `CheckForNull` is used on accessors and `Nullable` is used everywhere else. I think that jsr305 and FB are quite semantically broken (`@Nullable == @Nonnull(when = unknown), @CheckForNull == @Nonnull(when = maybe)`) and jsr305 is not approved and dormant, a lot of people are using `Nullable` as indicator that something can be null, and `CheckForNull` as something to actually force adding explicit check in code, but otherwise unneeded annotation. While reflecting on this, it seems that the best option would be using custom `@Nullable` annotation which annotated with `@Nonnull(when=Maybe)` for FB compatibility (I dunno if this will actually work this way). In any case, if you add FB annotations jar, Immutables will auto emit `@SuppressFBWarning` to generated classes to reduce some annoyances.

**Comment by elucash** [comment]
actually, as I verified that `@CheckForNull` can be placed anywhere I'll go fix it to simpler and non-replaced by `Nullable`
