### ISSUE TITLE
Add 'transient' keyword to hashCode field when prehash is enabled

### ISSUE THREAD

**Issue by ghost** [immutables/immutables#659]
When using  `@Value.Immutable(prehash = true)` `hashCode` is being using by persistent frameworks like spring data.

Adding 'transient' keyword to the transient fields like `hashCode` should solve that I believe.

**Comment by elucash** [comment]
sorry for not responding earlier, the problem with this is that I don't know how or if we should to restore this field upon deserialization. I mean using java binary serialization. Spring data probably only use this modifier to know if it should skip the field. But in order to do consistent functionality we need to check if deserialization paths can recreate consistent objects: we have some custom serialization proxies generated which potentially restore all the correct state, but I'm not sure 100%

**Comment by andrey-cabonline** [comment]
If I understand problem correctly, you should bother about serialization/deserialization only if class implements java.io.Serializable.
If it does not then it's safe to apply transient keyword.

If it does implement java.io.Serializable then generated class might have something like:
```java
private void readObject(java.io.ObjectInputStream in) throws IOException, ClassNotFoundException {
    in.defaultReadObject();
    setEageryCalculatedFields();
}
```

More on [readObject](https://docs.oracle.com/javase/8/docs/api/java/io/Serializable.html).
