### ISSUE TITLE
Can't deserialize json immutable map

### ISSUE THREAD

**Issue by nicolasrosado** [immutables/immutables#680]
Hi, 

I have a problem with an attribute of an immutable class annotated with @Value.Immutable.
See below : 

_@Value.Immutable
@JsonSerialize(as = ImmutableTestForm.class)
@JsonDeserialize(as = ImmutableTestForm.class)
public interface TestForm {
    @JsonProperty("targetUrl")
    String targetUrl();
    @JsonProperty("testValues")
    Map<String, String> testValues();
}_

The error below occured when I try to post the form above : 
"Http 415" Unsupported Media type error with JSON

I don't have the error when I try with a HashMap because the class generated by immutables use HashMap instead ImmutableMap.

Could tell me if is it possible to use Map ? And How I can use it ?

Thanks in advance,

**Comment by xbj110825** [comment]
I have the same problem when I use immutable object as @RequestBody in spring boot. The HTTP 415 status code and error message is confusing. I found the root cause is in AbstractJackson2HttpMessageConverter.java
```java
        @Override
	public boolean canRead(Type type, @Nullable Class<?> contextClass, @Nullable MediaType mediaType) {
		if (!canRead(mediaType)) {
			return false;
		}
		JavaType javaType = getJavaType(type, contextClass);
		AtomicReference<Throwable> causeRef = new AtomicReference<>();
		if (this.objectMapper.canDeserialize(javaType, causeRef)) { // this line return false
			return true;
		}
		logWarningIfNecessary(javaType, causeRef.get());
		return false;
	}
```
The causeRef message is `Cannot find a deserializer for non-concrete Collection type [collection type; class com.google.common.collect.ImmutableList, contains [simple type, class com.foo.bar]]`

I fix the problem after reading this issue https://github.com/immutables/immutables/issues/680
