### ISSUE TITLE
Avoid usage of java.util.Objects

### ISSUE THREAD

**Issue by jkolash** [immutables/immutables#685]
This is an android related issue, but not all released versions of android support java.util.Objects

There could be a style flag to avoid use of this class, or it could be avoided entirely

See:
https://developer.android.com/reference/java/util/Objects.html

**Comment by jkolash** [comment]
Looks like this is handled by simply including
```
        <dependency>
          <groupId>org.immutables</groupId>
          <artifactId>android-stub</artifactId>
          <version>2.5.5</version>
          <scope>provided</scope>
        </dependency>
```

I will close this issue.

**Comment by elucash** [comment]
Yes, that is the right solution. We trying to figure out from classpath if `java.util.Objects` is available, but it happens to be present because jdk1.7+ is used for compilation, albeit target Android platform have no such class. This forces us to detect `andoid.R`, in case when we creating libraries with no direct dependency on Android classes, we use `android-stub` to simulate that.
