### ISSUE TITLE
adding javax.validation.constraints.NotEmpty annotaion producing errors in generated code

### ISSUE THREAD

**Issue by mcgaw** [immutables/immutables#709]
Hi, there seems to have been some regression. I'm using immutables 2.5.5

```
@Value.Immutable
@BaseStyle
public abstract class UserImmutable {

    @NotEmpty
    abstract String getUsername();

}
```

is resulting in

```
/**
 * Immutable implementation of {@link UserImmutable}.
 * <p>
 * Use the builder to create immutable instances:
 * {@code User.builder()}.
 */
@SuppressWarnings({"all"})
@Generated({"Immutables.generator", "UserImmutable"})
public final class User extends UserImmutable {
  private final java.lang.@NotEmpty String username;
.
.
.
/**
   * @return The value of the {@code username} attribute
   */
  @Override
  java.lang.@NotEmpty String getUsername() {
    return username;
  }
.
.
.
}
```

`java.lang.` is being added into the generated field and method text. The import for the annotation is correctly generated. My `BaseStyle` is only to change the naming convention. I'm compiling using Maven, as directed in the docs.

**Comment by elucash** [comment]
Starting with spec version 2.0 (or 2.1 I don't remember exactly) Bean Validation annotation switched to use `ElementType.TYPE_USE`, which made them annotation on types, not elements. For your information, `java.lang.@NotEmpty String` is correct syntax for type annotations (Java 8) on fully qualified type names, where annotation inserted after a package name but before a simple name in a fully qualified name.  Please, can you specify errors you're seeing along with compiler/java versions(source/target) versions. Maybe there's some mixture of Java 6/7 source version compiled with Java 8 JDK or something like this. (also might be that new Bean Validation annotations are not applicable to sources compiled Java versions less than 8)

**Comment by mcgaw** [comment]
Hi Eugene, thanks for the quick response. I rather hastily used the word 'error'. In actual fact, the [Oval](http://oval.sourceforge.net/) library I'm using ignores the annotation if it is 'fully qualified' with `java.lang.@`. I admittedly wasn't familiar with this syntax. I'm guessing I can file a bug with Oval, although I'm rather curious what the advantage or reason behind fully qualifying the annotation was? It just seems to add noise to the source.

I also noticed that that if I use, for example, the Oval ootb validation annotations such as `net.sf.oval.constraint.NotEmpty` instead of `javax.validation.constraints.NotEmpty` then this annotation does not appear in the generated Immutable source, which I found rather surprising. Would you be able to comment on that?
Cheers for the cool lib!

**Comment by elucash** [comment]
1) in Immutables, we use imports post-processor which use some heuristics to find fully qualified names in generated source and simplify names automatically adding imports to the top. For this new syntax, post-processor is not smart enough, so it leaving it as is, and `java.lang.String` (with interspersed type annotation) is fully qualified as we're getting this from the internal mirror API (like reflection, but used in annotation processing) in a generic way (every type's toString/print operation returns fully qualified name) and we use them in generated source almost verbatim.

2. Only type annotations (`ElementType.TYPE_USE`) are transferred along the type itself. Other annotations (like `ElementType.FIELD`,`METHOD`... etc) are not auto transferred (only certain kinds, like `Nullable`). Most of the time (like in the case of Bean Validation v1.0 annotations), annotations are considered inherited, so implementation method considered as inheriting abstract accessor method's annotations. It depends how exactly framework treat annotations (sometimes it depends if annotations have `@Inherited` meta-annotation). In order to have custom annotations copied to generated accessors, you can try using `@Value.Style(passAnnotations = {` attribute to list annotation classes, please see documentation on [styles](http://immutables.github.io/style.html) and Javadoc for `passAnnotations`.

**Comment by mcgaw** [comment]
Hi, thanks for taking the time to explain why they are fully qualified. Either Oval needs to deal with this effectively or I'll need to investigate Hibernate Validator/Google autovalue. I've raised an issue with Oval including small unit test [project](https://github.com/sebthom/oval/issues/11) so I'll see what he comes back with in terms of supporting this.

I tried `@Value.Style(passAnnotations = {NotEmpty.class})` for the Oval annotation but it didn't seem to have any effect. Passing them through is not a big deal though, JSR 303 can be used no problem.

**Comment by mcgaw** [comment]
Mmm, this is a bit frustrating. I tried reworking with [bval](https://bval.apache.org/) and it displays the exact same behaviour as Oval believe it or not. It does not like the `java.lang.@` syntax. I'll try looking at the source code to see what the heck is going on.

**Comment by elucash** [comment]
If it compiles, it's not about the syntax. It may be the fact that you're using type annotations, not method or field level annotations. For example, if you use Bean Validation 1.0 implementations and Bean Validation 2.0 annotations api (which are `TYPE_USE`) the impl framework might not see those annotations as it's tries to get those from the elements, not types. I suggest to try to clearly delineate the problem, I it compiles, which version on annotations are used, does validation framework support these kind/version of annotations.

**Comment by mcgaw** [comment]
I'm not actually changing any annotation, I'm only manually removing `java.lang.@` syntax from the generated source file, then it starts working.

**Comment by elucash** [comment]
is it possible to prepare smallest project with all dependency included , so I can try to troubleshoot it? (can attach zip to the issue or give a link on some online repository)

**Comment by mcgaw** [comment]
OK, I've got to the bottom of it I think. I was using 2.0 validation api, which is not supported by Oval or bval. Why they were picking the 2.0 annotations up after removing the fully qualified `java.lang.` I have no idea! (And it's not that interesting now)
So, working with 1.1 of the spec, if I set them on bean style getters in the Immutable, and use `passAnnotations` in `@Value.Style` then they come through and bval picks them up.
I imagine things will be a bit cleaner once 2.0 spec is supported by bval but for the time being I can live with the `passAnnotations` hack.
My apologies, I should not have been using the 2.0 jar and wasting your time. But thanks very much for the attention and I will use Immutables in my project!

**Comment by Stephan202** [comment]
@elucash, not sure if I should file a new issue for this, but the introduction of `TYPE_USE` has another effect: since the annotations are now copied to the generated class' private fields, Hibernate Validator will report each violation _twice_: once for the field, and one for the getter methods. Right now this prevents us from upgrading to Validation API 2.0 / Hibernate Validator 6.

I'm willing to help fix this, but I'd first like to get your view on what the fix should look like. Blindly omitting all `TYPE_USE` annotations from generated fields is probably not desirable. Omitting all `javax.validation.constraints.*` annotations from generated code would do the trick (they're inherited from the `@Value.Immutable` interface/abstract class anyway), but that would not cater for custom constraint annotations. Perhaps the annotations to be omitted could be identified by them having the `javax.validation.Constraint` meta-annotation. Anyway, WDYT?

**Comment by elucash** [comment]
@Stephan202 thinking about it. This is harder than I ever thought it can be, having whilelist/blacklist or type annotations would be, probably, a practical solution. It's hard to understand how it was designed work when they annotate those annotations `@Target({ METHOD, FIELD, ANNOTATION_TYPE, CONSTRUCTOR, PARAMETER, TYPE_USE })` - should they apply to both type and element?

**Comment by mcgaw** [comment]
I must be missing something, why is it copied to the private field in 2.0?

**Comment by elucash** [comment]
It is copied along the type, because type annotation is a part of type, not element (ie. field has type `@NotEmpty String`, not that field is annotated with `@NotEmpty`). I clearly understand it was made for the purpose of making use cases as `Map<String, @NonEmpty String>` work. But on the other hand it's a huge mistake on the part of Bean Validation 2.0 spec, because it's not longer clear if annotation belong to type or element. It can be that there is a clear pathway of how it should be used and I don't know some important details, so if we have some additional on the subject it's good to know.

**Comment by mcgaw** [comment]
If I've only annotated the getter return type (or getter method) then I wouldn't expect the private field to be annotated (either field or type). I mean it doesn't make sense to me: the idea is that it's a bean, and properties in beans are defined by their getters. Private fields are an implementation detail really. I'm not really sure if validation annotations at the field level even make sense in terms of Java beans. I suppose a developer may wish to validate private fields for other reasons, although it would be turning into more of an assertion!
> because type annotation is a part of type

I'm not sure I agree with that, I mean the annotation only applies to particular usage scenarios. It's meta-data.
I know in past when using persistance frameworks it was quite common to annotate at the field level, because afaik you could persist the value at the field level (instead of the bean property) and it was also more readable I guess. Maybe this is influencing you?

**Comment by elucash** [comment]
I'm referring to "type annotation" as a special kind of annotation, please see "JSR 308: Annotations on Java Types" specification

**Comment by Stephan202** [comment]
@elucash if such annotation white-/blacklists are package-based that would go a very long way. Unfortunately for this particular issue it doesn't play very nice with setups where a single `@Value.Style` is used throughout a large project. (Because there'll inevitably be an edge case, and `@Value.Style` doesn't support composition/inheritance.)

Alternatives that I'm currently pondering:
1. Omission from anywhere in the generated code, based on the above-mentioned `@javax.validation.Constraint` meta-annotation.
2. Omission from private fields (and maybe methods/constructors/parameters?) in the generated code of _any_ `TYPE_USE` annotation.

I'm currently tending towards (2), as that seems to be both safer and more general: Immutables would nicely respect `TYPE_USE` on the public API of generated classes, without causing surprising behavior due to its implementation details. And in some sense this type of omission is (paradoxically) consistent with the fact that Immutables currently _adds_ `@JsonIgnore` and `@SuppressionWarnings` annotations (#694, #706) to private fields. In each case it's about preventing implementation details from leaking, be it at runtime (Jackson serialization, Hibernate Validation) or compile time (built-in `javac` warnings, Error prone analysis).

**Comment by mcgaw** [comment]
I quickly tried out [AutoValue](https://github.com/google/auto) just out of interest. Both validation 1.1 and 2.0 annotations on the property accessors (ie on the method) are respected and appear on the generated accessors. They are not copied to the private fields.
Currently AutoValue seems to ignore annotaions on the type, eg on the accessor return types (tried with the cannonical Map example)

**Comment by mcgaw** [comment]
@Stephan202 Can I close this issue, perhaps you want to open a new one for the copying of type annotations on the property accessor to the private field?

**Comment by Stephan202** [comment]
@mcgaw, yeah go ahead :+1: . I'll file a new ticket some time today.

**Comment by Stephan202** [comment]
Alright, I filed #712.

**Comment by mcgaw** [comment]
Cheers.
