### ISSUE TITLE
Use error-prone's @Var annotation in generated hashCode() method

### ISSUE THREAD

**Issue by vorburger** [immutables/immutables#716]
@elucash would you consider adding [error-prone's @Var annotation](http://errorprone.info/api/latest/com/google/errorprone/annotations/Var.html) for its [anti-final Var bug pattern](http://errorprone.info/bugpattern/Var) in generated `hashCode()` implementations:

    public int hashCode() {
        @Var int h = 5381;

Obviously only if `com.google.errorprone.annotations.Var` is on the classpath (auto detected..) just like you are doing for some of the other annotations you're automatically adding.

This would solve google/error-prone/issues/808 for me.

**Comment by elucash** [comment]
I very much in favor of it, as much as I like having most fields and most classes final, it genuinely freaks me out to see people polluting their code with finals on locals and params. Don't know if we ever use `final` on params or locals in Immutables for access from inner classes in order to be source-compatible with Java 7 (or 6). It can have some complications. Also, it would be massive code change in templates and will require testing with this check enabled and disabled. Another alternative (which I'm less compelled about, but still) is to have such checks suppressed.

**Comment by elucash** [comment]
to conclude, PR will be welcome, will require some time to review
