### ISSUE TITLE
non-@Value.Immutable class's @Value.Style is not propagated to @Value.Immutable subclass

### ISSUE THREAD

**Issue by nezda** [immutables/immutables#742]
Non-`@Value.Immutable` class's `@Value.Style` is not propagated to `@Value.Immutable` subclass.  Package option doesn't easily work for us.

```java
public abstract class NonValueBase {
  // this non-@Value.Immutable class's @Value.Style is not propagated to @Value.Immutable subclass
  @Value.Style(build = "buildInternal", typeImmutable = "*")
  public abstract static class StaticInnerNonValueBase {
    public abstract int id();
  }

  @Value.Immutable
  // have to uncomment this for it to compile
  //@Value.Style(build = "buildInternal", typeImmutable = "*")
  public abstract static class AbstractSubclass extends StaticInnerNonValueBase {
    public abstract String name();
  }

  public static void main(String[] args) {
    final Subclass subclass = Subclass.builder().id(1).name("foo").buildInternal();
    System.out.println(subclass);
  }
}
```

Containing non-`@Value.Immutable` outer class `@Value.Style`s are propagated to nested static inner `@Value.Immutable` classes.  i.e., this works

```java
@Value.Style(build = "buildInternal", typeImmutable = "*")
public abstract class NonValueBase {
  public abstract int id();

  @Value.Immutable
  //@Value.Style(build = "buildInternal", typeImmutable = "*")
  public abstract static class AbstractSubclass extends NonValueBase {
    public abstract String name();
  }

  public static void main(String[] args) {
    final Subclass subclass = Subclass.builder().id(1).name("foo").buildInternal();
    System.out.println(subclass);
  }
}
```

**Comment by elucash** [comment]
thank you for reporting this. For now, it's by design that style covers only target elements and their parents (top level, package, parent package) ignoring any hierarchy. Potentially, subtypes may be extended by classes with different styles, in a different package, or another module. There are can be many supertypes (including interfaces) thus can be very tricky to define which style to use.

Historically, I try to stay away from complex overriding rules for styles or implementing merging (cascading) of styles (which would be both good and bad). Hopefully, package annotations and meta-annotated style annotations help to keep things manageable. I somehow scared to implement something along these lines adding subtyping axis to style discovery )

**Comment by nezda** [comment]
Understood - feel free to close this then.
