### ISSUE TITLE
Inhibit-classpath isn't suitable for a modular context

### ISSUE THREAD

**Issue by io7m** [immutables/immutables#772]
Hello!

Up to now, I've been using the `inhibit-classpath` feature to stop Immutables from adding `javax.annotation.Generated` on generated code. Unfortunately, it seems that this no longer works in a modular context: It's trying to inhibit classes that are on the classpath, but unfortunately those classes are actually on the module path now.

See the following trivial example that fails on JDK 10:

https://github.com/io7m/immutables-bug-20180514

You can see that I'm inhibiting `javax.annotation`, but the annotations end up on the generated classes anyway. The compilation then fails because the annotations that were added are not exported from `java.base`.

**Comment by elucash** [comment]
Thank you for reporting this! The problem here (non-obvious though) is that extensions are read from the annotation processor runtime classpath, so this should be thought of as an extension to annotation processor, not to the code under question. For better or for worse, extensions now also read from (should work for javac/maven at least, and with the provided repro) from the compilation classpath if possible. This fix is to be released.
I also recommend moving to whitelist approach (by using `Style.allowedClasspathAnnotations`) if this would make any sense.

**Comment by io7m** [comment]
Ah, thanks, didn't know about whitelisting. I'll give that a short: I would almost always want the whitelist to be empty anyway (don't pick up any annotations from anywhere).

**Comment by elucash** [comment]
there's note in javadoc that empty whitelist is like everything is allowed, to make real "empty" whitelist, you have to put some bogus entry there, like `java.lang.Override` or another annotation irrelevant in the context

**Comment by io7m** [comment]
Ah, yeah, thanks. Unfortunately... Still doesn't work. 

I don't know how this works internally, but I should reiterate that `javax.annotation.processing.Generated` isn't on the classpath anymore, but is part of the `java.base` module (and to confuse things further, isn't actually exported by it, so won't ever be visible to applications). I'm not sure how this interacts with annotation processors... Do they execute as if they were on the classpath, or as if they were on the module path?

**Comment by elucash** [comment]
when I do lookup using annotation processing api, it says the class is there. I would expect sort of api to check access to this module from the module being compiled, but I'm not there yet (it can be also an annotation processing bug)

**Comment by elucash** [comment]
at first I added `requires static java.compiler` (iirc) just to be sure it's exported from somewhere, that compiled, but not the goal, of course

**Comment by io7m** [comment]
I'm suspicious that the annotation processor is running in classpath mode (so it can see every class, even those that aren't exported), but obviously the resulting generated code is being compiled in module path mode (so gives errors for the non-exported `Generated` annotation).

It's not clear to me why, if the above is true, the whitelisting and blacklisting would fail though...

**Comment by io7m** [comment]
You're right... I've no idea what I was doing wrong, but it does seem to be working now. Thanks!

**Comment by jest** [comment]
Unfortunately, using `allowedClasspathAnnotations` is often a great burden, as styles are not merged anyhow: attaching to package is often not enough, as I have to go down to every interface which also has `@Value.Style` and add `allowedClasspathAnnotations` there.

For me this is a bit of mixing infrastructure with a code; as a developer, I should care about `@Value.Immutable` attributes. Styles are for me part of build infrastructure (although I must use them in code for "exceptional" use of `allParameters`).

What I'd like to achieve is to express `inhibit-classpath` with an already existing interface to build tools, i.e. annotation processor options (javac's `-A`). Instead of placing extension on the classpath, one could pass the processor options on the command line:

```
javac -A extensions.org.immutables.inhibit-classpath=javax.annotation,javax.processing.annotation,org.immutables.value.Generated [...]
```
and have it applied across all compiled classes.

I'm working in OSGi (bnd) where the content of "foreign" JAR is not directly on the classpath, so to use extensions mechanism globally I have to repackage original Immutables processor by adding `META-INF/extensions/org.immutables.inhibit-classpath` file there... generally not a recommended thing to do.

Do you think it is reasonable to add a short piece of adapter code to `ExtensionLoader.findExtensions` to look in those options? E.g.

```java
Map<String,String> opts = StaticEnvironment.processing().getOptions();
String extOpt = opts.get("extensions." + resource);
if (extOpt != null) {
  extensions.addAll(Arrays.asList(extOpt.split(",")));
}
```

This would greatly simplified the build infra for us. If it makes sense to you @elucash, I can produce a PR.
