### ISSUE TITLE
Unable to create public default constructor

### ISSUE THREAD

**Issue by johno1985** [immutables/immutables#774]
I am using the @Value.Immutable annotation on my abstract class and I need a public default constructor to be generated. There does not appear to be a way to do this

**Comment by elucash** [comment]
public default constructors are not used with immutable objects, because all data has to be initialized before instance returned to the caller, not after. If you need constructor and to have it public, please refer to this part of the documentation discussing constuctor: http://immutables.github.io/immutable.html#constructor. If there's a need for mutable types, you can create modifiable companion classes: http://immutables.github.io/immutable.html#modifiable

**Comment by johno1985** [comment]
yeah, that makes sense since we're dealing with final fields. I did try the Modifiable companion class but I still cannot create a default public constructor. Essentially I am trying to Scala-like value object to use in a Jersey MVC application._

**Comment by elucash** [comment]
there's 2 style options that can make generated modifiable classes more like java beans:

```java
@Value.Style(
  create = "new", // rename create method to "new", turning factory into plain public constuctor,
  beanFriendlyModifiables = true // setters will return void instead of instance if needed for strict javabean framework
)
```

On the other hand, you can just bind immutable classes to JSON (like most people do). Immutables support Jackson and Gson (there's also Gson/JAX-RS integration provided by `org.immutables:gson` module)  http://immutables.github.io/json.html

**Comment by johno1985** [comment]
thanks, 'create = "new"' seems to work. Just a note, I'm not using JSON, I'm developing an MVC application that binds form objects to POJOs

**Comment by pauldingemans** [comment]
Johno1985,
Would it be ok for you to close this issue now? Or do you have additional insights on this topic which require further discussion?

**Comment by johno1985** [comment]
Hi @pauldingemans, apologies for not confirming sooner. Yes, it is OK to close. Thanks @elucash
