### ISSUE TITLE
Generated classes can contain mutable fields

### ISSUE THREAD

**Issue by k21** [immutables/immutables#78]
If I use the `@Value.Immutable` annotation on an abstract class that contains member variables or has a superclass that contains member variables, the generated `Immutable*` subclass will also contain those member variables and will not in fact be immutable. Is it possible to show a warning message or preferably fail the generation if the generated class would inherit any member variables?

**Comment by elucash** [comment]
There are many ways to make immutable class non immutable and sometimes we cannot guarantee "total" immutability in a broadest sense, but I think issuing a warning is a very good idea. Initially it was decided to not issue any kind of warning because occasionally, one need to create some mutable field to cache something manually or alike. After that, various features was added like `@Lazy` and `@Derived` attributes, which rendered manual fields useless and violating immutability.
+1 to add a warning.
Thanks for suggestion!

**Comment by elucash** [comment]
Released in 2.0
