### ISSUE TITLE
querydsl with immutables

### ISSUE THREAD

**Issue by asereda-gs** [immutables/immutables#812]
Hi Eugene,

I was wondering if you ever thought about extending (extracting) [mongo repositories](https://immutables.github.io/mongo.html) functionality to support other data-sources (like ElasticSearch, SQL etc.) ? 

After building AST ([Constraint](https://github.com/immutables/immutables/blob/master/mongo/src/org/immutables/mongo/repository/internal/Constraints.java)) using provided repository one can generate a native query for destination data-source (as it is done now for mongo).

I understand there are many unanswered questions like read vs write or relational DB vs document DB, but does it sound sensible (at least on paper) ?

**Comment by elucash** [comment]
I absolutely would like this (also #4)
I like your idea about it to be extensible, like we can allow contributing runtime lib mapping for any custom repo along with some metadata which will instruct generator to generate typesafe stuff linked to the runtime support. We need to collect some sort of sketches/sample mapping/feature sets which can guide us toward the design.

**Comment by asereda-gs** [comment]
Perhaps not directly related to this issue but what do you think about Quoted Domain Specific Language (QDSL) like [Quill](http://getquill.io/) (for scala) and [Jinq](http://www.jinq.org/) (for java) ? Pretty much LINQ approach to querying databases. What is your opinion about codegen vs native language AST ?

**Comment by elucash** [comment]
I'm curious what is "Quoted" in this context. In general, we can try to approach general query DSL. I just see too many different concepts being compared so it's hard to reason about. Of course if we found a way to abstract repository generation to adapt to different databases, then our generated query builder/DLS might become powerful/flexible enough to be generic DSL.
Native language AST is about parsing bytecode (like trying to see whats compiled in that lambda like in Jinq) or is it about using native database query language in string literals?

**Comment by asereda-gs** [comment]
I was trying to compare two approaches for defining queries (expressions) against a data-source : 

1. codegened DSL. in the scope for current proposal.
2. Expression tree from code. Native language AST (as you mentioned serialized lambda and bytecode). Out of scope here (for immutables in general).

(2) may have it's own issues and complications, I think.

**Comment by elucash** [comment]
Yeah, I've though of similar, basically API is what is needed and move more logic to runtime, where some reflection is quite ok and arguably could be easier to test (debugability can still be an area where generated code can be somewhat better). I assume repos are non-core functionality of immutables and largely IO bound and heavily depend on the performance of DB drivers, so codegen cannot give real benefits over runtime descriptors and some reflection.
If you have more ideas about specific shape of APIs, let's collect some Gists, putting links here

**Comment by asereda-gs** [comment]
Sure. I'll provide some links.

One more question regarding criteria API. For attribute `foo`, currently code generates multiple constraint methods (`fooIn`, `fooNotIn`, `fooPresent` etc.) in Criteria. What do you think about chaining methods like below:

```java
criteria()
   .foo().equalTo("myfoo")
   .bar().isTrue()
   .or()
   .qux().greaterThan(123)

// instead of "single dimension"
criteria()
   .foo("bar")
   .barIsTrue()
   .or()
   .quxGreaterThan(123)
```

That means `foo()` will return eg. `StringConstraint`. There are pros and cons obviously.

* Pros. There are fewer methods in criteria which makes it cleaner for user. 
* Cons. Code and API becomes more complicated (to generated and support).

**Comment by asereda-gs** [comment]
@elucash I've invited you to my personal project [querydsl](https://github.com/asereda-gs/querydsl/).
Please let me know what you think about flat vs fluent approach of constraints. Right now I'd like to focus more on API.

**Comment by elucash** [comment]
@asereda-gs I remember I had some thoughts about flat vs nested builder styles. So I remember I was deciding what style to choose initially. I received some feedback from other folks at that time, but in nutshell it was "whatever works" so I had to choose something for myself. Here's what I remember was important (at the time)

* The approach with nested matchers looked like most flexible, yet problematic.
  - Here "nested matchers" means commonly used notation similar to `.field("name", eq(5)).field`
  - String literals can be replaced with something more strongly typed as special property mirrors etc
  - Usually hard to type, inadequate autocompletion, i.e. there is some help, but not as fluent to type
  - more naturally supports nesting of condition via method call composition`.and(field("a",eq(1), or(field("b",eq(2)), field("c",eq(3))))` yet this is not necessarily more readable. But the combinatory flexibility is great once past the overhead of syntax.
* Nested builder style has the advantage of that list of properties are seen at the glance when auto completing. (`field1().eq(2)`)
  - Obviously, requires more classes, yet can actually save the number of methods where descriptor for each type will have them already declared. I.e. no need to generate full production of methods (attribute x per attribute criterion).
  - In my experimentation it looks more cluttered and verbose compared to flat (`field1().equalTo(2) vs field1EqualTo(2)`), but on the other hand it can be considered more clear. Arguably, some more "clutter" factor arises from then they combined together (`field1().equalTo(2).field2().notEqual(3)`). 
  - Auto-formatting is not great for this option, where formatting engine lacks understanding that specific pair of calls are to be on a single line, when breaking gracefully between them, it's either/or: Choose between each call is on a separate line, or all calls together wrapped to a new line only when reaching line limit. Or resort to manual formatting and make sure auto-formatting will not reformat those lines. (some years ago when there was less code formatting options available, I even remember using `  //` at the end of lines which would prevent joining of manually wrapped lines.)
* I thought it was very good idea for criteria objects to be immutable and creating new modified copy on each "modification", such criteria object can be stored in memory and passed from one object to another, where modifiable implementation would force the construct-and-use (or construct-and-not-change-until-used) kind of treating. Ideally, this concerns should be orthogonal to the shape of API, but some API choices can make immutability harder to implement or would require additional API "syntax".
* In the end it was somewhat plausible to use flat query dsl because it was quite straightforward to use. It has good auto-completion with discoverability concept, a little bit cluttered list of DSL methods, but easily narrowed down by specific attribute [prefix] choice. Easy to understand that each such method would return a new copy (once you know that criteria objects are immutable).
  - This has good code formatting story, each call can be auto-formatted on a new line and structure is quite visible (for a limited use)
  - Solution is inherently limited, once you need more complex query, you need to construct DYI json string. This can be a good tradeoff, on the other hand can be quite annoying if sidestepping happens often.

One of the interesting options which I looked at, but have not explored in details is using fields per attribute, which require some Java gymnastics to implement, but should be possible. Also experience can be traumatizing to people who cannot stand "unencapsulated" fields, though nowadays I guess more and more "acceptable" to use fields in more contexts:

```java

where.fieldB.equalTo(1)
    .fieldB.contains("2")
    .field3.a
```

Have no idea how auto-formatting and other stuff works with these. Implementation wise, this requires state transitions only on method calls, while fields do "action-path" selection.

```
// names are bogus, just putting some random stuff from the top of my head
// and maybe some parts are irrelevant
abstract class DocumentCriteria<Host extends DocumentCriteria<Host>> {...}
abstract class ValueCriteria<Host extends DocumentCriteria<Host>> {...}

class StringCriteria<Host> extends ValueCriteria<Host> {
   Host contains(String substring)...
   Host isEmpty()...
   ...
} 

class BookCriteria extends DocumentCriteria<BookCriteria> {
    public final StringCriteria<BookCriteria> author;
    public final StringCriteria<BookCriteria> publisher;
    .....
    private BookCriteria() {
          author = Criterias.stringCriteria(this); // some ugly stuff like this escaping consructor...
          ...
    }
}
```

It's unclear how `or` and other stuff should work, just something I though about but never went past some snippets. Maybe I hit some limitation and decided it's not worth it, but I don't remember ))

**Comment by asereda-gs** [comment]
@elucash thanks for your detailed feedback. 

Criteria object will remain immutable as before (I also like this part).

### Flat vs Nested Builders
Overall I'm inclined towards nested builders(`field.equalTo(42)` or `field()`). Mostly because it allows more encapsulation of functionalities (like `StringCriteria` vs `NumberCriteria` ) and pojo Criteria doesn't become bloated with dozens of methods for large models. 

Regarding autoformatting, while appreciated and helpful it shouldn't drive the design of the API. 

Also an advantage of nested builders is that one can directly reference document field in java API (which brings us to next point below). 

### Projections and Aggregations
Some users have requested support for projections and aggregations. Should immutable support basic aggregations like `min / max / avg / count` etc ? 
What about projections ? 
If so, what is the returned model ? (generic Struct / Map ? )

What is your opinion about supporting this functionality ? 

### Extensibility
Like raw json in current criteria API user should be able to provide custom queries. I don't know yet how to implement it in a generic fashion.

**Comment by asereda-gs** [comment]
@elucash pls take a look at #881 

There are some sketches for Criteria API (created separate `criteria` maven model). 

It needs more work but I'd like to get your feedback if things are going in the right direction.

**Comment by asereda-gs** [comment]
Feature implemented as part of [Criteria API](https://immutables.github.io/criteria.html)

**Comment by aranikrishna** [comment]
Does it make sense to have criteria API extended to have Joins (inner and out join)  like jooq? 
Of course as mongo and elastic doesnt have a way to push down but this has be in-memory.

**Comment by asereda-gs** [comment]
The plan is add SQL backend which allows joins. 

For efficient joins you really need a query optimizer eg how to decide nested loop join vs [hash-join](https://en.wikipedia.org/wiki/Hash_join) vs [merge-join](https://sqlserverfast.com/epr/merge-join/).

What you're referring to can be solved with SQL Backend and [Calcite](https://calcite.apache.org/)
