### ISSUE TITLE
.Style(get = {"is*","get*"}) not generating any code

### ISSUE THREAD

**Issue by cocoviper** [immutables/immutables#82]
I just discovered this wonderful project and I'm trying to implement it in my project and i wanted to add getters and setters on my Immutable. The setters are there but the getters are not added.

Here is the annotations I'm using:
```Java
@Value.Immutable(visibility = Value.Immutable.ImplementationVisibility.PUBLIC)
@Value.Style(get = {"is*","get*"},init = "set*")
abstract class Transaction {
```

I'm using version 1.1.2

**Comment by elucash** [comment]
Hi, thank you for the interest. `get = {"is*","get*"}` defines detection pattern, so without get patterns, when you have
```java
interface A {
   int getA(); // defines "getA" attribute
   int c(); // defines "c" attribute
}
```
when use pattern as `get = {"is*","get*"}` get and is prefixed accessors will be detected, and attribute name will be derived from accessor.
```java
@Value.Style(get = {"is*","get*"}, init = "set*")
interface B {
   int getA(); // defines "a" attribute
   int c(); // defines "c" attribute
   int isEmpty(); // defines "empty" attribute
}
```
Please, note, that actual accessors will be unchanged and will be used as is. First of all, toString will contain simple names like "a", "c" or "empty", also in this way, when you define `getAttribute` accessor, builder will have `setAttribute` initializer method rather than `setGetAttribute`, which would be generated without "get*" prefix detection.

And don't forget to eventually create your own concise style annotation (meta annotated with `@Value.Style` definition you want) to place on classes or whole packages (using `package-info.java`).

Let us know if it doesn't work as described or if it's unclear.

**Comment by cocoviper** [comment]
I understand now , thank you for the quick response!
