### ISSUE TITLE
Add JsonTypeName jackson annotation as a default propagated annotation

### ISSUE THREAD

**Issue by StephenOTT** [immutables/immutables#874]
Consider something like

```java
@Value.Immutable
@Value.Style(typeImmutable = "AttackPattern", validationMethod = Value.Style.ValidationMethod.NONE, additionalJsonAnnotations = {JsonTypeName.class})
@JsonTypeName("attack-pattern")
@JsonSerialize(as = AttackPattern.class) @JsonDeserialize(builder = AttackPattern.Builder.class)
public interface AttackPatternSdo extends DomainObject {
...
```

Would be great is `@JsonTypeName` was a default injected annotation for jackson as it would be commonly used in scenarios where the `value.style.typeImmutable` prop is being used.

**Comment by elucash** [comment]
I assume that `additionalJsonAnnotations` works for this case, right? There's some fear, or better say concerns about auto-copying Jackson annotations, it caused some trouble in the past, so we add only minimum of Jackson annotations which are "known" to not cause problems, but that also means that if we will keep adding such annotations, we might potentially break other code/some expectations about these (interaction of reflective/annotation frameworks and tools (like Jackson binding and other third-party tools can get very hairy, even if this looks quite innocent).

**Comment by StephenOTT** [comment]
@elucash given the "problems" you mentioned, then i would think that it should just be left in its current implementation.  It is not a big issue to add the "additionalJsonAnnotations" to each class.  It is a bit of duplication, but not really a issue or concern.

Would be great if the Docs could be updated to have the list of Annotations that are auto-copied!

Thanks!

**Comment by elucash** [comment]
@StephenOTT just as reminder, documentation mentions this many times: do not put styles on each class except only for fiddling/experimenting, put styles either using custom [meta-annotatated] style annotation or on a parent package (or both: putting meta-annotated style annotation on a package) (if this works for you build tool). http://immutables.github.io/style.html

**Comment by elucash** [comment]
@StephenOTT if you need to name class use pattern `typeAbstract="*Sdo", typeImmutable="*"` which should produce what you want (as far as I can understand from your the example)

**Comment by StephenOTT** [comment]
@elucash +1 for the custom annotations.  Agreed.

For the `typeAbstract="*Sdo", typeImmutable="*"` I do not have any abstract classes.  Everything is a interface that `@Value.Immutable` is generating the immutable classes from.  How does typeAbstract help in this?

**Comment by elucash** [comment]
`typeAbstract` is stands for abstract value type (http://immutables.github.io/immutable.html#abstract-value-type), which is expressed either using interface or abstract class. (and actually on the bytecode level, interface is a class with `is_abstract`, `is_interface` flags set on it). In styles, `typeAbstract` is detection pattern (alongside with `get` and some others) rather than formatting pattern. When detecting, pattern is applied to recognize the "core" name of value type, which is then used in generated `toString` and for some other needs. If you use `typeAbstract="*Sdo", typeImmutable="*"` on `AttackPatternSdo` abstract value type, `AttackPattern` would be detected and captured as pattern (`*`), so this would be the name of value type, then when generating it will use `"*"` pattern for immutable type which would generate `AttackPattern` immutable class (as opposed to `ImmutableAttackPattern` for default template `Immutable*` which have this "Immutable" prefix added.

**Comment by StephenOTT** [comment]
@elucash 👍 👍 👍 .  Thank you for that perfect explanation!

Would recomend that the javadoc and docs capture that specific example.  Unless i missed it?  It seems like a very easy pattern to miss.  "typeAbstract can be used in combination with typImmutable="*" to provide a class name for the Immutable.  "

@elucash thanks for great community support!
