### ISSUE TITLE
Add custom methods to builders?

### ISSUE THREAD

**Issue by Gaff** [immutables/immutables#933]
Is it possible to add methods to a builder class? For example I'd like to be able to do:

```
foo = ImmutableData.builder()
            .user("user")
            .usingDailyUpdates(...) //conveniently sets a bunch of fields
            .build();
```

Or

```
bar = ImmutableData.copyOf(foo)
          .withUser("user")
          .withDateShiftedBy(4); //Custom logic here for mutating the object
```

Is this possible?

**Comment by elucash** [comment]
Yes, you can use super builder or extending builder. I.e. you define static. inner Builder class inside abstract value type and declare you convenient methods there. In order to use generated initializer methods you need to either declare abstract signatures of those for super builder, or just use those from base class in case of extending builder. Please, refer to builder related section in the guide, there are examples of super and extending builders.

**Comment by Gaff** [comment]
@elucash  - I see thanks. The super builder works well.

I couldn't get the extending builder to work though because the generated builder is `final`. Is there some trick / annotation to solve this?

**Comment by elucash** [comment]
It will not be final if you recompile it, `final` is from previous compilation before you added proper `static class Builder extends ImmutableVal.Builde { ` etc

**Comment by Gaff** [comment]
@elucash  - one more question (sorry) - is it possible to add additional `withXXX(...)` methods to an immutable type?

**Comment by elucash** [comment]
additional methods can be added just by declaring on the abstract value type as non-abstract methods on the abstract class or default methods the interface. In order to get signatures of the other `withXxx` methods to use in an implementation of `withUberXxxYxx`, use either.

- casting `this` to the generated type. 
- or declare abstract matching signatures of `with` in abstract value types
- extending not yet generated `WithXXX` interface which would bring abstract signatures automatically matching generated `withXxx` methods `@Immutable interface Data extends WithData {..`
