### ISSUE TITLE
Wrong code generation for Android API < 19

### ISSUE THREAD

**Issue by almozavr** [immutables/immutables#96]
On API < 19 `Builder` checks values for `null` with 
```java
Objects.requireNonNull
```
The *problem* is method is available [from API 19](https://developer.android.com/reference/java/util/Objects.html#requireNonNull(T)) (android 4.4.x) only, and makes a crash on e.g. 4.2 devices. 
Would be great if you could check if all code-generated methods using api >=15 (for most shared platform versions).

**Comment by elucash** [comment]
Previously we supported api levels < 19 only by using Guava, but lately Android is getting more attention from Immutables, so it's reasonable to fix this (along with some other inconsistencies), rather than require Guava. There still could be some java7 API appear somewhere, but I hope it will work for many cases.

Released in version 2.0.5. Thank you for bug report!

**Comment by almozavr** [comment]
Confirm `2.0.5` works, thanks for a lightning speed :+1:

**Comment by pushbit** [comment]
I'm using `@Style(clearBuilder = true, jdkOnly = true)` and I believe the `jdkOnly` part is causing `java.util.Objects` usage.  I use these style attributes so that `clear()` clears `Collection` instances instead of instantiating new Guava `Immutable*` builders.  I was hoping to use Android API level down to 16.  Am I stuck between two conflicting concerns?
